/*                 Joe's Window Manager Configuration
 *
 * This program configures JWM using pugixml and FLTK
 *
 *         Copyright (C) 2016  Israel <israeldahl@gmail.com>
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * This has been developed as a part of the ToriOS Project
 *
 *
 * You may redistribute this, but you must keep this comment in place
 * Jesus is my Lord, and if you don't like it feel free to ignore it.
 */
// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef jwm_desktop_h
#define jwm_desktop_h
#include <FL/Fl.H>
#include <libintl.h>
#include <string>
#include <stdlib.h>
#include <iostream>
#include "../include/jwmrc.hpp"
#include "../include/desktop.hpp"
#include <algorithm>
#include "../include/ui.hpp"
#include "../data/icons/jsm-desktop.xpm"
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Menu_Button.H>

class DesktopUI : public JSM_Desktop {
public:
  std::string thisBG;std::string FILEMANAGER;unsigned int DESKTOPNUM; 
  Fl_Double_Window* make_window();
  Fl_Double_Window *desktop_window;
  Fl_Box *background_displayer_thingie;
  Fl_Box *color_display1;
  Fl_Box *color_display2;
private:
  inline void cb_Choose_i(Fl_Button*, void*);
  static void cb_Choose(Fl_Button*, void*);
  inline void cb_Choose1_i(Fl_Button*, void*);
  static void cb_Choose1(Fl_Button*, void*);
  inline void cb_Choose2_i(Fl_Button*, void*);
  static void cb_Choose2(Fl_Button*, void*);
public:
  Fl_Button *fm_pref;
private:
  inline void cb_fm_pref_i(Fl_Button*, void*);
  static void cb_fm_pref(Fl_Button*, void*);
public:
  Fl_Check_Button *icons_check;
private:
  inline void cb_icons_check_i(Fl_Check_Button*, void*);
  static void cb_icons_check(Fl_Check_Button*, void*);
public:
  Fl_Output *current_bg;
  Fl_Check_Button *check_desktops;
private:
  inline void cb_check_desktops_i(Fl_Check_Button*, void*);
  static void cb_check_desktops(Fl_Check_Button*, void*);
public:
  Fl_Value_Input *num_desktop_w;
private:
  inline void cb_num_desktop_w_i(Fl_Value_Input*, void*);
  static void cb_num_desktop_w(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *num_desktop_h;
private:
  inline void cb_num_desktop_h_i(Fl_Value_Input*, void*);
  static void cb_num_desktop_h(Fl_Value_Input*, void*);
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
  inline void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
public:
  Fl_Menu_Button *menu_button;
private:
  inline void cb_menu_button_i(Fl_Menu_Button*, void*);
  static void cb_menu_button(Fl_Menu_Button*, void*);
public:
  int total_desktops();
  void make_menu(Fl_Menu_Button* o);
  static void desktop_menu_cb(Fl_Menu_ *o);
  void menu_cb(Fl_Menu_ *o);
  void set_BGS(std::string bg, unsigned int num);
};
#endif
