/*                 Joe's Window Manager Configuration
 *
 * This program configures JWM using pugixml and FLTK
 *
 *         Copyright (C) 2016  Israel <israeldahl@gmail.com>
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * This has been developed as a part of the ToriOS Project
 *
 *
 * You may redistribute this, but you must keep this comment in place
 * Jesus is my Lord, and if you don't like it feel free to ignore it.
 */
// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef jwm_window_h
#define jwm_window_h
#include <FL/Fl.H>
#include <libintl.h>
#include <string>
#include <stdlib.h>
#include <iostream>
#include "../include/jwmrc.hpp"
#include "../include/window.hpp"
#include "../data/icons/jsm-windows.xpm"
#include "../include/ui.hpp"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Output.H>

class WindowUI : public JSM_Window {
protected:
  std::string browser_line; 
  std::string context; 
private:
  int JWMVERSION; 
  int whichElement; 
public:
  Fl_Double_Window* add_option_window();
  Fl_Double_Window *add_opt_window;
  Fl_Browser *options_available;
private:
  inline void cb_options_available_i(Fl_Browser*, void*);
  static void cb_options_available(Fl_Browser*, void*);
public:
  Fl_Browser *options_desc;
  Fl_Input *icon_value;
  Fl_Slider *opacity_value;
  Fl_Value_Input *desktop_num;
private:
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
  inline void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
public:
  Fl_Menu_Button *layer_chooser;
  static unsigned char menu_layer_chooser_i18n_done;
  static Fl_Menu_Item menu_layer_chooser[];
private:
  inline void cb_below_i(Fl_Menu_*, void*);
  static void cb_below(Fl_Menu_*, void*);
  inline void cb_normal_i(Fl_Menu_*, void*);
  static void cb_normal(Fl_Menu_*, void*);
  inline void cb_above_i(Fl_Menu_*, void*);
  static void cb_above(Fl_Menu_*, void*);
public:
  Fl_Output *layer_value;
private:
  inline void cb__i(Fl_Button*, void*);
  static void cb_(Fl_Button*, void*);
public:
  Fl_Double_Window* add_class_window();
  Fl_Double_Window *class_win;
  Fl_Input *input_to_add_class;
private:
  inline void cb_OK1_i(Fl_Button*, void*);
  static void cb_OK1(Fl_Button*, void*);
public:
  Fl_Double_Window* add_program_window();
  Fl_Double_Window *prog_win;
  Fl_Input *input_to_add_prog;
private:
  inline void cb_OK2_i(Fl_Button*, void*);
  static void cb_OK2(Fl_Button*, void*);
  inline void cb_Program_i(Fl_Button*, void*);
  static void cb_Program(Fl_Button*, void*);
public:
  Fl_Double_Window* add_context_window();
  Fl_Double_Window *context_add_win;
  static unsigned char menu_Button_i18n_done;
  static Fl_Menu_Item menu_Button[];
private:
  inline void cb_move_i(Fl_Menu_*, void*);
  static void cb_move(Fl_Menu_*, void*);
  inline void cb_move1_i(Fl_Menu_*, void*);
  static void cb_move1(Fl_Menu_*, void*);
  inline void cb_move2_i(Fl_Menu_*, void*);
  static void cb_move2(Fl_Menu_*, void*);
  inline void cb_move3_i(Fl_Menu_*, void*);
  static void cb_move3(Fl_Menu_*, void*);
  inline void cb_close_i(Fl_Menu_*, void*);
  static void cb_close(Fl_Menu_*, void*);
  inline void cb_fullscreen_i(Fl_Menu_*, void*);
  static void cb_fullscreen(Fl_Menu_*, void*);
  inline void cb_minimize_i(Fl_Menu_*, void*);
  static void cb_minimize(Fl_Menu_*, void*);
  inline void cb_maximize_i(Fl_Menu_*, void*);
  static void cb_maximize(Fl_Menu_*, void*);
  inline void cb_roll_i(Fl_Menu_*, void*);
  static void cb_roll(Fl_Menu_*, void*);
  inline void cb_move4_i(Fl_Menu_*, void*);
  static void cb_move4(Fl_Menu_*, void*);
  inline void cb_resize_i(Fl_Menu_*, void*);
  static void cb_resize(Fl_Menu_*, void*);
  inline void cb_show_i(Fl_Menu_*, void*);
  static void cb_show(Fl_Menu_*, void*);
  inline void cb_Show_i(Fl_Menu_*, void*);
  static void cb_Show(Fl_Menu_*, void*);
  inline void cb_Show1_i(Fl_Menu_*, void*);
  static void cb_Show1(Fl_Menu_*, void*);
  inline void cb_Show2_i(Fl_Menu_*, void*);
  static void cb_Show2(Fl_Menu_*, void*);
  inline void cb_move5_i(Fl_Menu_*, void*);
  static void cb_move5(Fl_Menu_*, void*);
  inline void cb_move6_i(Fl_Menu_*, void*);
  static void cb_move6(Fl_Menu_*, void*);
  inline void cb_move7_i(Fl_Menu_*, void*);
  static void cb_move7(Fl_Menu_*, void*);
  inline void cb_move8_i(Fl_Menu_*, void*);
  static void cb_move8(Fl_Menu_*, void*);
  inline void cb_restart_i(Fl_Menu_*, void*);
  static void cb_restart(Fl_Menu_*, void*);
  inline void cb_exit_i(Fl_Menu_*, void*);
  static void cb_exit(Fl_Menu_*, void*);
  inline void cb_Show3_i(Fl_Menu_*, void*);
  static void cb_Show3(Fl_Menu_*, void*);
  inline void cb_Maximize_i(Fl_Menu_*, void*);
  static void cb_Maximize(Fl_Menu_*, void*);
  inline void cb_Maximize1_i(Fl_Menu_*, void*);
  static void cb_Maximize1(Fl_Menu_*, void*);
  inline void cb_Maximize2_i(Fl_Menu_*, void*);
  static void cb_Maximize2(Fl_Menu_*, void*);
  inline void cb_Maximize3_i(Fl_Menu_*, void*);
  static void cb_Maximize3(Fl_Menu_*, void*);
  inline void cb_Maximize4_i(Fl_Menu_*, void*);
  static void cb_Maximize4(Fl_Menu_*, void*);
  inline void cb_Maximize5_i(Fl_Menu_*, void*);
  static void cb_Maximize5(Fl_Menu_*, void*);
  inline void cb_Send_i(Fl_Menu_*, void*);
  static void cb_Send(Fl_Menu_*, void*);
  inline void cb_Send1_i(Fl_Menu_*, void*);
  static void cb_Send1(Fl_Menu_*, void*);
  inline void cb_Send2_i(Fl_Menu_*, void*);
  static void cb_Send2(Fl_Menu_*, void*);
  inline void cb_Send3_i(Fl_Menu_*, void*);
  static void cb_Send3(Fl_Menu_*, void*);
  inline void cb_Restore_i(Fl_Menu_*, void*);
  static void cb_Restore(Fl_Menu_*, void*);
public:
  Fl_Output *add_button;
  Fl_Output *add_context_button;
private:
  inline void cb_Cancel1_i(Fl_Button*, void*);
  static void cb_Cancel1(Fl_Button*, void*);
  inline void cb_OK3_i(Fl_Button*, void*);
  static void cb_OK3(Fl_Button*, void*);
  inline void cb_1_i(Fl_Button*, void*);
  static void cb_1(Fl_Button*, void*);
  static unsigned char menu_Button1_i18n_done;
  static Fl_Menu_Item menu_Button1[];
  inline void cb_11_i(Fl_Menu_*, void*);
  static void cb_11(Fl_Menu_*, void*);
  inline void cb_12_i(Fl_Menu_*, void*);
  static void cb_12(Fl_Menu_*, void*);
  inline void cb_111_i(Fl_Menu_*, void*);
  static void cb_111(Fl_Menu_*, void*);
  inline void cb_2_i(Fl_Menu_*, void*);
  static void cb_2(Fl_Menu_*, void*);
  inline void cb_21_i(Fl_Menu_*, void*);
  static void cb_21(Fl_Menu_*, void*);
  inline void cb_22_i(Fl_Menu_*, void*);
  static void cb_22(Fl_Menu_*, void*);
  inline void cb_3_i(Fl_Menu_*, void*);
  static void cb_3(Fl_Menu_*, void*);
  inline void cb_31_i(Fl_Menu_*, void*);
  static void cb_31(Fl_Menu_*, void*);
  inline void cb_33_i(Fl_Menu_*, void*);
  static void cb_33(Fl_Menu_*, void*);
  inline void cb_4_i(Fl_Menu_*, void*);
  static void cb_4(Fl_Menu_*, void*);
  inline void cb_5_i(Fl_Menu_*, void*);
  static void cb_5(Fl_Menu_*, void*);
public:
  Fl_Input *action_input;
  Fl_Input *add_mask;
  static unsigned char menu_Item_i18n_done;
  static Fl_Menu_Item menu_Item[];
private:
  inline void cb_Title_i(Fl_Menu_*, void*);
  static void cb_Title(Fl_Menu_*, void*);
  inline void cb_Icon_i(Fl_Menu_*, void*);
  static void cb_Icon(Fl_Menu_*, void*);
  inline void cb_Border_i(Fl_Menu_*, void*);
  static void cb_Border(Fl_Menu_*, void*);
  inline void cb_Close_i(Fl_Menu_*, void*);
  static void cb_Close(Fl_Menu_*, void*);
  inline void cb_Maximize6_i(Fl_Menu_*, void*);
  static void cb_Maximize6(Fl_Menu_*, void*);
  inline void cb_Minimize_i(Fl_Menu_*, void*);
  static void cb_Minimize(Fl_Menu_*, void*);
  inline void cb_Root_i(Fl_Menu_*, void*);
  static void cb_Root(Fl_Menu_*, void*);
public:
  Fl_Double_Window* button_order_window();
  Fl_Double_Window *button_orderer;
  Fl_Input *ordering;
private:
  inline void cb_Cancel2_i(Fl_Button*, void*);
  static void cb_Cancel2(Fl_Button*, void*);
  inline void cb_OK4_i(Fl_Button*, void*);
  static void cb_OK4(Fl_Button*, void*);
public:
  Fl_Double_Window* configure_context();
  Fl_Double_Window *context_config;
  static unsigned char menu_Button2_i18n_done;
  static Fl_Menu_Item menu_Button2[];
private:
  inline void cb_move9_i(Fl_Menu_*, void*);
  static void cb_move9(Fl_Menu_*, void*);
  inline void cb_movea_i(Fl_Menu_*, void*);
  static void cb_movea(Fl_Menu_*, void*);
  inline void cb_moveb_i(Fl_Menu_*, void*);
  static void cb_moveb(Fl_Menu_*, void*);
  inline void cb_movec_i(Fl_Menu_*, void*);
  static void cb_movec(Fl_Menu_*, void*);
  inline void cb_close1_i(Fl_Menu_*, void*);
  static void cb_close1(Fl_Menu_*, void*);
  inline void cb_fullscreen1_i(Fl_Menu_*, void*);
  static void cb_fullscreen1(Fl_Menu_*, void*);
  inline void cb_minimize1_i(Fl_Menu_*, void*);
  static void cb_minimize1(Fl_Menu_*, void*);
  inline void cb_maximize1_i(Fl_Menu_*, void*);
  static void cb_maximize1(Fl_Menu_*, void*);
  inline void cb_roll1_i(Fl_Menu_*, void*);
  static void cb_roll1(Fl_Menu_*, void*);
  inline void cb_moved_i(Fl_Menu_*, void*);
  static void cb_moved(Fl_Menu_*, void*);
  inline void cb_resize1_i(Fl_Menu_*, void*);
  static void cb_resize1(Fl_Menu_*, void*);
  inline void cb_show1_i(Fl_Menu_*, void*);
  static void cb_show1(Fl_Menu_*, void*);
  inline void cb_Show4_i(Fl_Menu_*, void*);
  static void cb_Show4(Fl_Menu_*, void*);
  inline void cb_Show5_i(Fl_Menu_*, void*);
  static void cb_Show5(Fl_Menu_*, void*);
  inline void cb_Show6_i(Fl_Menu_*, void*);
  static void cb_Show6(Fl_Menu_*, void*);
  inline void cb_movee_i(Fl_Menu_*, void*);
  static void cb_movee(Fl_Menu_*, void*);
  inline void cb_movef_i(Fl_Menu_*, void*);
  static void cb_movef(Fl_Menu_*, void*);
  inline void cb_move10_i(Fl_Menu_*, void*);
  static void cb_move10(Fl_Menu_*, void*);
  inline void cb_move11_i(Fl_Menu_*, void*);
  static void cb_move11(Fl_Menu_*, void*);
  inline void cb_restart1_i(Fl_Menu_*, void*);
  static void cb_restart1(Fl_Menu_*, void*);
  inline void cb_exit1_i(Fl_Menu_*, void*);
  static void cb_exit1(Fl_Menu_*, void*);
  inline void cb_Show7_i(Fl_Menu_*, void*);
  static void cb_Show7(Fl_Menu_*, void*);
  inline void cb_Maximize7_i(Fl_Menu_*, void*);
  static void cb_Maximize7(Fl_Menu_*, void*);
  inline void cb_Maximize8_i(Fl_Menu_*, void*);
  static void cb_Maximize8(Fl_Menu_*, void*);
  inline void cb_Maximize9_i(Fl_Menu_*, void*);
  static void cb_Maximize9(Fl_Menu_*, void*);
  inline void cb_Maximizea_i(Fl_Menu_*, void*);
  static void cb_Maximizea(Fl_Menu_*, void*);
  inline void cb_Maximizeb_i(Fl_Menu_*, void*);
  static void cb_Maximizeb(Fl_Menu_*, void*);
  inline void cb_Maximizec_i(Fl_Menu_*, void*);
  static void cb_Maximizec(Fl_Menu_*, void*);
  inline void cb_Send4_i(Fl_Menu_*, void*);
  static void cb_Send4(Fl_Menu_*, void*);
  inline void cb_Send5_i(Fl_Menu_*, void*);
  static void cb_Send5(Fl_Menu_*, void*);
  inline void cb_Send6_i(Fl_Menu_*, void*);
  static void cb_Send6(Fl_Menu_*, void*);
  inline void cb_Send7_i(Fl_Menu_*, void*);
  static void cb_Send7(Fl_Menu_*, void*);
  inline void cb_Restore1_i(Fl_Menu_*, void*);
  static void cb_Restore1(Fl_Menu_*, void*);
public:
  Fl_Output *button;
  Fl_Output *context_button;
private:
  inline void cb_Cancel3_i(Fl_Button*, void*);
  static void cb_Cancel3(Fl_Button*, void*);
  inline void cb_OK5_i(Fl_Button*, void*);
  static void cb_OK5(Fl_Button*, void*);
  inline void cb_6_i(Fl_Button*, void*);
  static void cb_6(Fl_Button*, void*);
  static unsigned char menu_Button3_i18n_done;
  static Fl_Menu_Item menu_Button3[];
  inline void cb_13_i(Fl_Menu_*, void*);
  static void cb_13(Fl_Menu_*, void*);
  inline void cb_14_i(Fl_Menu_*, void*);
  static void cb_14(Fl_Menu_*, void*);
  inline void cb_112_i(Fl_Menu_*, void*);
  static void cb_112(Fl_Menu_*, void*);
  inline void cb_23_i(Fl_Menu_*, void*);
  static void cb_23(Fl_Menu_*, void*);
  inline void cb_24_i(Fl_Menu_*, void*);
  static void cb_24(Fl_Menu_*, void*);
  inline void cb_221_i(Fl_Menu_*, void*);
  static void cb_221(Fl_Menu_*, void*);
  inline void cb_32_i(Fl_Menu_*, void*);
  static void cb_32(Fl_Menu_*, void*);
  inline void cb_34_i(Fl_Menu_*, void*);
  static void cb_34(Fl_Menu_*, void*);
  inline void cb_331_i(Fl_Menu_*, void*);
  static void cb_331(Fl_Menu_*, void*);
  inline void cb_41_i(Fl_Menu_*, void*);
  static void cb_41(Fl_Menu_*, void*);
  inline void cb_51_i(Fl_Menu_*, void*);
  static void cb_51(Fl_Menu_*, void*);
public:
  Fl_Input *value_1;
  Fl_Input *mask;
  Fl_Double_Window* make_gtk_theme_window();
  Fl_Double_Window *theme_window;
  Fl_Browser *theme_browser;
private:
  inline void cb_Cancel4_i(Fl_Button*, void*);
  static void cb_Cancel4(Fl_Button*, void*);
  inline void cb_OK6_i(Fl_Button*, void*);
  static void cb_OK6(Fl_Button*, void*);
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *window_window;
  Fl_Button *a_title_color1;
private:
  inline void cb_a_title_color1_i(Fl_Button*, void*);
  static void cb_a_title_color1(Fl_Button*, void*);
public:
  Fl_Button *a_title_color2;
private:
  inline void cb_a_title_color2_i(Fl_Button*, void*);
  static void cb_a_title_color2(Fl_Button*, void*);
public:
  Fl_Button *a_font_color;
private:
  inline void cb_a_font_color_i(Fl_Button*, void*);
  static void cb_a_font_color(Fl_Button*, void*);
public:
  Fl_Button *a_border_color;
private:
  inline void cb_a_border_color_i(Fl_Button*, void*);
  static void cb_a_border_color(Fl_Button*, void*);
public:
  Fl_Slider *active_o_slider;
private:
  inline void cb_active_o_slider_i(Fl_Slider*, void*);
  static void cb_active_o_slider(Fl_Slider*, void*);
public:
  Fl_Value_Input *active_o_slider_v;
private:
  inline void cb_active_o_slider_v_i(Fl_Value_Input*, void*);
  static void cb_active_o_slider_v(Fl_Value_Input*, void*);
public:
  Fl_Button *inactive_color;
private:
  inline void cb_inactive_color_i(Fl_Button*, void*);
  static void cb_inactive_color(Fl_Button*, void*);
public:
  Fl_Button *inactive_color2;
private:
  inline void cb_inactive_color2_i(Fl_Button*, void*);
  static void cb_inactive_color2(Fl_Button*, void*);
public:
  Fl_Button *inactive_font_color;
private:
  inline void cb_inactive_font_color_i(Fl_Button*, void*);
  static void cb_inactive_font_color(Fl_Button*, void*);
public:
  Fl_Button *inactive_border_color;
private:
  inline void cb_inactive_border_color_i(Fl_Button*, void*);
  static void cb_inactive_border_color(Fl_Button*, void*);
public:
  Fl_Slider *inactive_o_slider;
private:
  inline void cb_inactive_o_slider_i(Fl_Slider*, void*);
  static void cb_inactive_o_slider(Fl_Slider*, void*);
public:
  Fl_Value_Input *inactive_o_slider_v;
private:
  inline void cb_inactive_o_slider_v_i(Fl_Value_Input*, void*);
  static void cb_inactive_o_slider_v(Fl_Value_Input*, void*);
public:
  Fl_Button *max_a_image;
private:
  inline void cb_max_a_image_i(Fl_Button*, void*);
  static void cb_max_a_image(Fl_Button*, void*);
public:
  Fl_Button *max_image;
private:
  inline void cb_max_image_i(Fl_Button*, void*);
  static void cb_max_image(Fl_Button*, void*);
public:
  Fl_Button *min_image;
private:
  inline void cb_min_image_i(Fl_Button*, void*);
  static void cb_min_image(Fl_Button*, void*);
public:
  Fl_Button *close_image;
private:
  inline void cb_close_image_i(Fl_Button*, void*);
  static void cb_close_image(Fl_Button*, void*);
public:
  Fl_Button *inactive_border_color2;
private:
  inline void cb_inactive_border_color2_i(Fl_Button*, void*);
  static void cb_inactive_border_color2(Fl_Button*, void*);
public:
  Fl_Button *a_border_color2;
private:
  inline void cb_a_border_color2_i(Fl_Button*, void*);
  static void cb_a_border_color2(Fl_Button*, void*);
public:
  Fl_Button *button_actions;
private:
  inline void cb_button_actions_i(Fl_Button*, void*);
  static void cb_button_actions(Fl_Button*, void*);
public:
  Fl_Button *button_order;
private:
  inline void cb_button_order_i(Fl_Button*, void*);
  static void cb_button_order(Fl_Button*, void*);
public:
  Fl_Slider *t_slider;
private:
  inline void cb_t_slider_i(Fl_Slider*, void*);
  static void cb_t_slider(Fl_Slider*, void*);
public:
  Fl_Value_Input *t_slider_v;
private:
  inline void cb_t_slider_v_i(Fl_Value_Input*, void*);
  static void cb_t_slider_v(Fl_Value_Input*, void*);
public:
  Fl_Slider *b_slider;
private:
  inline void cb_b_slider_i(Fl_Slider*, void*);
  static void cb_b_slider(Fl_Slider*, void*);
public:
  Fl_Value_Input *b_slider_v;
private:
  inline void cb_b_slider_v_i(Fl_Value_Input*, void*);
  static void cb_b_slider_v(Fl_Value_Input*, void*);
public:
  Fl_Menu_Button *focus_menu;
  static unsigned char menu_focus_menu_i18n_done;
  static Fl_Menu_Item menu_focus_menu[];
private:
  inline void cb_Click_i(Fl_Menu_*, void*);
  static void cb_Click(Fl_Menu_*, void*);
  inline void cb_Mouse_i(Fl_Menu_*, void*);
  static void cb_Mouse(Fl_Menu_*, void*);
  inline void cb_Click1_i(Fl_Menu_*, void*);
  static void cb_Click1(Fl_Menu_*, void*);
  inline void cb_Mouse1_i(Fl_Menu_*, void*);
  static void cb_Mouse1(Fl_Menu_*, void*);
public:
  Fl_Menu_Button *resize_menu;
  static unsigned char menu_resize_menu_i18n_done;
  static Fl_Menu_Item menu_resize_menu[];
private:
  inline void cb_Make_i(Fl_Menu_*, void*);
  static void cb_Make(Fl_Menu_*, void*);
  inline void cb_Show8_i(Fl_Menu_*, void*);
  static void cb_Show8(Fl_Menu_*, void*);
public:
  Fl_Menu_Button *move_menu;
  static unsigned char menu_move_menu_i18n_done;
  static Fl_Menu_Item menu_move_menu[];
private:
  inline void cb_Make1_i(Fl_Menu_*, void*);
  static void cb_Make1(Fl_Menu_*, void*);
  inline void cb_Show9_i(Fl_Menu_*, void*);
  static void cb_Show9(Fl_Menu_*, void*);
public:
  Fl_Menu_Button *snap_menu;
  static unsigned char menu_snap_menu_i18n_done;
  static Fl_Menu_Item menu_snap_menu[];
private:
  inline void cb_The_i(Fl_Menu_*, void*);
  static void cb_The(Fl_Menu_*, void*);
  inline void cb_The1_i(Fl_Menu_*, void*);
  static void cb_The1(Fl_Menu_*, void*);
  inline void cb_No_i(Fl_Menu_*, void*);
  static void cb_No(Fl_Menu_*, void*);
public:
  Fl_Value_Input *snap_int;
private:
  inline void cb_snap_int_i(Fl_Value_Input*, void*);
  static void cb_snap_int(Fl_Value_Input*, void*);
public:
  Fl_Slider *corner_slider;
private:
  inline void cb_corner_slider_i(Fl_Slider*, void*);
  static void cb_corner_slider(Fl_Slider*, void*);
public:
  Fl_Browser *groups_browser;
private:
  inline void cb_groups_browser_i(Fl_Browser*, void*);
  static void cb_groups_browser(Fl_Browser*, void*);
public:
  Fl_Button *group_add;
private:
  inline void cb_group_add_i(Fl_Button*, void*);
  static void cb_group_add(Fl_Button*, void*);
public:
  Fl_Button *rm_group;
private:
  inline void cb_rm_group_i(Fl_Button*, void*);
  static void cb_rm_group(Fl_Button*, void*);
public:
  Fl_Browser *opt_browser;
  Fl_Button *opt_add;
private:
  inline void cb_opt_add_i(Fl_Button*, void*);
  static void cb_opt_add(Fl_Button*, void*);
public:
  Fl_Button *rm_opt;
private:
  inline void cb_rm_opt_i(Fl_Button*, void*);
  static void cb_rm_opt(Fl_Button*, void*);
public:
  Fl_Browser *name_browser;
  Fl_Button *prog_add;
private:
  inline void cb_prog_add_i(Fl_Button*, void*);
  static void cb_prog_add(Fl_Button*, void*);
public:
  Fl_Button *rm_prog;
private:
  inline void cb_rm_prog_i(Fl_Button*, void*);
  static void cb_rm_prog(Fl_Button*, void*);
public:
  Fl_Browser *class_browser;
  Fl_Button *class_add;
private:
  inline void cb_class_add_i(Fl_Button*, void*);
  static void cb_class_add(Fl_Button*, void*);
public:
  Fl_Button *rm_class;
private:
  inline void cb_rm_class_i(Fl_Button*, void*);
  static void cb_rm_class(Fl_Button*, void*);
public:
  Fl_Slider *a_b_slider;
private:
  inline void cb_a_b_slider_i(Fl_Slider*, void*);
  static void cb_a_b_slider(Fl_Slider*, void*);
public:
  Fl_Value_Output *a_b_slider_v;
  Fl_Slider *a_t_slider;
private:
  inline void cb_a_t_slider_i(Fl_Slider*, void*);
  static void cb_a_t_slider(Fl_Slider*, void*);
public:
  Fl_Value_Output *a_t_slider_v;
  Fl_Input *default_icon;
  Fl_Button *default_icon_button;
private:
  inline void cb_default_icon_button_i(Fl_Button*, void*);
  static void cb_default_icon_button(Fl_Button*, void*);
public:
  Fl_Input *default_icon_win;
  Fl_Button *default_icon_button_win;
private:
  inline void cb_default_icon_button_win_i(Fl_Button*, void*);
  static void cb_default_icon_button_win(Fl_Button*, void*);
  static unsigned char menu_title_i18n_done;
  static Fl_Menu_Item menu_title[];
public:
  static Fl_Menu_Item *motif;
private:
  inline void cb_motif_i(Fl_Menu_*, void*);
  static void cb_motif(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *flat;
private:
  inline void cb_flat_i(Fl_Menu_*, void*);
  static void cb_flat(Fl_Menu_*, void*);
public:
  Fl_Output *decorations;
  static unsigned char menu_border_i18n_done;
  static Fl_Menu_Item menu_border[];
  static Fl_Menu_Item *motif_border;
private:
  inline void cb_motif_border_i(Fl_Menu_*, void*);
  static void cb_motif_border(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *flat_border;
private:
  inline void cb_flat_border_i(Fl_Menu_*, void*);
  static void cb_flat_border(Fl_Menu_*, void*);
public:
  Fl_Output *decorations_border;
private:
  inline void cb_Cancel5_i(Fl_Button*, void*);
  static void cb_Cancel5(Fl_Button*, void*);
  inline void cb_OK7_i(Fl_Button*, void*);
  static void cb_OK7(Fl_Button*, void*);
  inline void cb_Change_i(Fl_Button*, void*);
  static void cb_Change(Fl_Button*, void*);
public:
  Fl_Double_Window* mouse_bindings_window();
  Fl_Double_Window *action_window;
  Fl_Button *context_close;
private:
  inline void cb_context_close_i(Fl_Button*, void*);
  static void cb_context_close(Fl_Button*, void*);
public:
  Fl_Button *context_minimize;
private:
  inline void cb_context_minimize_i(Fl_Button*, void*);
  static void cb_context_minimize(Fl_Button*, void*);
public:
  Fl_Button *context_maximize;
private:
  inline void cb_context_maximize_i(Fl_Button*, void*);
  static void cb_context_maximize(Fl_Button*, void*);
public:
  Fl_Button *context_title;
private:
  inline void cb_context_title_i(Fl_Button*, void*);
  static void cb_context_title(Fl_Button*, void*);
public:
  Fl_Button *context_icon;
private:
  inline void cb_context_icon_i(Fl_Button*, void*);
  static void cb_context_icon(Fl_Button*, void*);
public:
  Fl_Button *context_border;
private:
  inline void cb_context_border_i(Fl_Button*, void*);
  static void cb_context_border(Fl_Button*, void*);
public:
  Fl_Button *context_root;
private:
  inline void cb_context_root_i(Fl_Button*, void*);
  static void cb_context_root(Fl_Button*, void*);
public:
  Fl_Browser *context_browser;
private:
  inline void cb_context_browser_i(Fl_Browser*, void*);
  static void cb_context_browser(Fl_Browser*, void*);
  inline void cb_7_i(Fl_Button*, void*);
  static void cb_7(Fl_Button*, void*);
  inline void cb_8_i(Fl_Button*, void*);
  static void cb_8(Fl_Button*, void*);
  inline void cb_9_i(Fl_Button*, void*);
  static void cb_9(Fl_Button*, void*);
  inline void cb_Cancel6_i(Fl_Button*, void*);
  static void cb_Cancel6(Fl_Button*, void*);
  inline void cb_OK8_i(Fl_Button*, void*);
  static void cb_OK8(Fl_Button*, void*);
public:
  void menu_cb(const char* action, Fl_Input * o);
  void button_choice_cb(int buttonnum, Fl_Output* o);
  void save_context();
  void add_context();
};
#endif
