/*                 Joe's Window Manager Configuration
 *
 * This program configures JWM using pugixml and FLTK
 *
 *         Copyright (C) 2016  Israel <israeldahl@gmail.com>
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * This has been developed as a part of the ToriOS Project
 *
 *
 * You may redistribute this, but you must keep this comment in place
 * Jesus is my Lord, and if you don't like it feel free to ignore it.
 */
// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef jwm_settings_h
#define jwm_settings_h
#include <FL/Fl.H>
#include <libintl.h>
#include "../include/ui.hpp"
#include "../include/common.hpp"
#include "../data/icons/jwm-settings-manager.xpm"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class SettingsUI : public FLTK_FUNCTIONS {
  JSM_UI ui; 
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *settings_window;
private:
  inline void cb_Panel_i(Fl_Button*, void*);
  static void cb_Panel(Fl_Button*, void*);
  inline void cb_Keyboard_i(Fl_Button*, void*);
  static void cb_Keyboard(Fl_Button*, void*);
  inline void cb_Icons_i(Fl_Button*, void*);
  static void cb_Icons(Fl_Button*, void*);
  inline void cb_Desktop_i(Fl_Button*, void*);
  static void cb_Desktop(Fl_Button*, void*);
  inline void cb_Touchpad_i(Fl_Button*, void*);
  static void cb_Touchpad(Fl_Button*, void*);
  inline void cb_Fonts_i(Fl_Button*, void*);
  static void cb_Fonts(Fl_Button*, void*);
  inline void cb_Windows_i(Fl_Button*, void*);
  static void cb_Windows(Fl_Button*, void*);
  inline void cb_Themes_i(Fl_Button*, void*);
  static void cb_Themes(Fl_Button*, void*);
  inline void cb_Autostart_i(Fl_Button*, void*);
  static void cb_Autostart(Fl_Button*, void*);
  inline void cb_Users_i(Fl_Button*, void*);
  static void cb_Users(Fl_Button*, void*);
  inline void cb_System_i(Fl_Button*, void*);
  static void cb_System(Fl_Button*, void*);
  inline void cb_Popups_i(Fl_Button*, void*);
  static void cb_Popups(Fl_Button*, void*);
public:
  bool isAdduser(Fl_Button *o);
  void adduser();
  bool isInfo(Fl_Button *o);
  void addinfo();
  int showSettings();
};
#endif
