language: cpp
sudo: required
dist: trusty
compiler: gcc
addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - gcc-multilib
    - g++-multilib
    - libc6
    - libfltk-images1.3
    - libfltk1.3
    - libfltk1.3-dev
    - libfltk1.3-compat-headers
    - libgcc1
    - libstdc++6
    - libx11-dev
    - libxpm-dev
    - fluid
    - pkg-config
before_script:
- mkdir build && cd build
script:
- cmake ..
- make -j$(nproc)
- make DESTDIR=appdir install ; find appdir/
- wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
- chmod a+x linuxdeployqt*.AppImage
- unset LD_LIBRARY_PATH
- "./linuxdeployqt*.AppImage ./appdir/usr/share/applications/jwm-settings-manager.desktop
  -bundle-non-qt-libs"
- "./linuxdeployqt*.AppImage ./appdir/usr/share/applications/jwm-settings-manager.desktop
  -appimage"
after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - mkdir Deploy
  - mv -v JWM_Settings_Manage*.AppImage* Deploy/
- curl --upload-file "{$(echo out/* | tr ' ' ',')}" https://transfer.sh/
notifications: 
email: false
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

before_deploy:
- if [ -z "$TRAVIS_TAG" ]; then export TRAVIS_TAG="continuous"; git tag -f $TRAVIS_TAG; fi
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: out/*
  skip_cleanup: true
  prerelease: true
  overwrite: true
  on:
    repo: Israel-D/jwm-settings-manager
    branch: master
    tags: true
