language: cpp
sudo: required
dist: trusty
compiler: gcc
addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - gcc-multilib
    - g++-multilib
    - libc6
    - libfltk-images1.3
    - libfltk1.3
    - libfltk1.3-dev
    - libfltk1.3-compat-headers
    - libgcc1
    - libstdc++6
    - libx11-dev
    - libxpm-dev
    - fluid
    - pkg-config
before_script:
  - mkdir build && cd build
script:
  - cmake ..
  - make -j$(nproc)
  - make DESTDIR=appdir install ; find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/jwm-settings-manager.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/jwm-settings-manager.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./JWM Settings Manager*.AppImage https://transfer.sh/JWM Settings Manager-git.$(git rev-parse --short HEAD)-x86_64.AppImage
notifications: 
email: false
