language: cpp
sudo: required
dist: trusty
compiler: gcc
addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - gcc-multilib
    - g++-multilib
    - libc6
    - libfltk-images1.3
    - libfltk1.3
    - libfltk1.3-dev
    - libfltk1.3-compat-headers
    - libgcc1
    - libstdc++6
    - libx11-dev
    - libxpm-dev
    - fluid
    - pkg-config
before_script:
- mkdir build && cd build
script:
- cmake ..
- make
after_success:
- make_appimage.sh
deploy:
  matrix:
  - provider: bintray
    skip_cleanup: true
    user: israeldahl
    file: ".bintray.yml"
    on:
      all_branches: true
  - provider: releases
    skip_cleanup: true
    file: deploy/*.AppImage
    file_glob: true
    on:
      tags: true
      all_branches: true
  key:
    secure: SRsWxbcYGE85nAKRXvC0JH68IcZg2Uq7Ecg/CuZUaQqrxHDdfGVejKBiVD/LgB48+hlgwcU7sv507IToQr7A5MCuQXFYmEe7G0htKyP5nJ8szCRZVve35z3wJO93LKWlFEvhw3iBYzaR5mfScDJRPIwLgIjWngqx3ZYJSmuIEIsgJnWsJIi62AFmK1pNGCfk9ERmb/QkjWJ9b6Wic6oHMlsSNApoivzgrT8zHrYI1Xc5TJxWpMzifo6wvpptoXp/OAxUoJb3KrH5F4kCE8T7x0fP+O5qO+o95Bbzuvh+cZoPSazTm/RLdgBoZx85uUxkPa99bJYW1oKkIBi5guVpRHcW9lvjxID7r7oEj9y9guT1ulEBH56hKAoPMmYri6NqreFCMhbCIYi8T0Aoz2R67xBATN/jHirTrmsfZcPM+dWUKGgzJW8xJ/Vf9CsZwIy6ZSiU50D8yc8wTb013u+zWlWavVNT1DwDcdcikVf926da7yf7pTWGJzAQlrtIydoJI2B9oMLk00Krz3jNfOUPaYtfwhzicEbks3RXt9W+tj3x3E6FkxOyTo00fg74ntX6+CiHK3tQ29kgikuvYdD/s8d+2ZzGeUN27g0czY4hvqpoZ6xTC6YiljStZDEKuTva++Wpb1P3W2AX7YqBClvfTkZI/S3sRBWAwmA81/e6l94=
notifications: 
email: false
