.TH jwm-settings-manager 1 "May 24, 2015" "version 1.0.0" "User Commands"
.SH NAME
jwm-settings-manager \- configure JWM easily

.SH SYNOPSIS
.B JWM Settings Manager
[OPTIONS]
.SH DESCTIPTION
A tool to easily configure JWM.  Built using FLTK and Tinyxml2,
this fast, and light, but doesn't sacrifice aesthetics.
.PP
configure JWM easily

.SH OPTIONS
.TP

.TP
\-a  --autostart   show autostart settings
.TP
\-d  --desktop     show desktop settings
.TP
\-f  --font        show font settings
.TP
\-h  --help        show this listing
.TP
\-i  --icons       show icon settings
.TP
\-k  --keyboard    show keyboard settings
.TP
\-m  --mouse       show mouse settings
.TP
\-p  --panel       show panel settings
.TP
\-t  --themes      show theme settings
.TP
\-w  --window      show window settings
.TP
\-r  --recover     recover settings file
.TP
\-v  --version     show version number
.TP
\-c  --copyright   show copyright information
.TP
.B X ONLY OPTION
.TP
\--halt           show shutdown menu

.SH AUTHOR
israeldahl
