# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lovejesus/computerstuff/bzr/github-jwm-settings-manager

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lovejesus/computerstuff/bzr/github-jwm-settings-manager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lovejesus/computerstuff/bzr/github-jwm-settings-manager/CMakeFiles /home/lovejesus/computerstuff/bzr/github-jwm-settings-manager/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lovejesus/computerstuff/bzr/github-jwm-settings-manager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named JSM

# Build rule for target.
JSM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JSM
.PHONY : JSM

# fast build rule for target.
JSM/fast:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/build
.PHONY : JSM/fast

#=============================================================================
# Target rules for targets named jwm-settings-manager

# Build rule for target.
jwm-settings-manager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jwm-settings-manager
.PHONY : jwm-settings-manager

# fast build rule for target.
jwm-settings-manager/fast:
	$(MAKE) -f CMakeFiles/jwm-settings-manager.dir/build.make CMakeFiles/jwm-settings-manager.dir/build
.PHONY : jwm-settings-manager/fast

fltk/jwm-autostart.o: fltk/jwm-autostart.cxx.o
.PHONY : fltk/jwm-autostart.o

# target to build an object file
fltk/jwm-autostart.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-autostart.cxx.o
.PHONY : fltk/jwm-autostart.cxx.o

fltk/jwm-autostart.i: fltk/jwm-autostart.cxx.i
.PHONY : fltk/jwm-autostart.i

# target to preprocess a source file
fltk/jwm-autostart.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-autostart.cxx.i
.PHONY : fltk/jwm-autostart.cxx.i

fltk/jwm-autostart.s: fltk/jwm-autostart.cxx.s
.PHONY : fltk/jwm-autostart.s

# target to generate assembly for a file
fltk/jwm-autostart.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-autostart.cxx.s
.PHONY : fltk/jwm-autostart.cxx.s

fltk/jwm-desktop.o: fltk/jwm-desktop.cxx.o
.PHONY : fltk/jwm-desktop.o

# target to build an object file
fltk/jwm-desktop.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-desktop.cxx.o
.PHONY : fltk/jwm-desktop.cxx.o

fltk/jwm-desktop.i: fltk/jwm-desktop.cxx.i
.PHONY : fltk/jwm-desktop.i

# target to preprocess a source file
fltk/jwm-desktop.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-desktop.cxx.i
.PHONY : fltk/jwm-desktop.cxx.i

fltk/jwm-desktop.s: fltk/jwm-desktop.cxx.s
.PHONY : fltk/jwm-desktop.s

# target to generate assembly for a file
fltk/jwm-desktop.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-desktop.cxx.s
.PHONY : fltk/jwm-desktop.cxx.s

fltk/jwm-fonts.o: fltk/jwm-fonts.cxx.o
.PHONY : fltk/jwm-fonts.o

# target to build an object file
fltk/jwm-fonts.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-fonts.cxx.o
.PHONY : fltk/jwm-fonts.cxx.o

fltk/jwm-fonts.i: fltk/jwm-fonts.cxx.i
.PHONY : fltk/jwm-fonts.i

# target to preprocess a source file
fltk/jwm-fonts.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-fonts.cxx.i
.PHONY : fltk/jwm-fonts.cxx.i

fltk/jwm-fonts.s: fltk/jwm-fonts.cxx.s
.PHONY : fltk/jwm-fonts.s

# target to generate assembly for a file
fltk/jwm-fonts.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-fonts.cxx.s
.PHONY : fltk/jwm-fonts.cxx.s

fltk/jwm-icons.o: fltk/jwm-icons.cxx.o
.PHONY : fltk/jwm-icons.o

# target to build an object file
fltk/jwm-icons.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-icons.cxx.o
.PHONY : fltk/jwm-icons.cxx.o

fltk/jwm-icons.i: fltk/jwm-icons.cxx.i
.PHONY : fltk/jwm-icons.i

# target to preprocess a source file
fltk/jwm-icons.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-icons.cxx.i
.PHONY : fltk/jwm-icons.cxx.i

fltk/jwm-icons.s: fltk/jwm-icons.cxx.s
.PHONY : fltk/jwm-icons.s

# target to generate assembly for a file
fltk/jwm-icons.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-icons.cxx.s
.PHONY : fltk/jwm-icons.cxx.s

fltk/jwm-keyboard.o: fltk/jwm-keyboard.cxx.o
.PHONY : fltk/jwm-keyboard.o

# target to build an object file
fltk/jwm-keyboard.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-keyboard.cxx.o
.PHONY : fltk/jwm-keyboard.cxx.o

fltk/jwm-keyboard.i: fltk/jwm-keyboard.cxx.i
.PHONY : fltk/jwm-keyboard.i

# target to preprocess a source file
fltk/jwm-keyboard.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-keyboard.cxx.i
.PHONY : fltk/jwm-keyboard.cxx.i

fltk/jwm-keyboard.s: fltk/jwm-keyboard.cxx.s
.PHONY : fltk/jwm-keyboard.s

# target to generate assembly for a file
fltk/jwm-keyboard.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-keyboard.cxx.s
.PHONY : fltk/jwm-keyboard.cxx.s

fltk/jwm-menu.o: fltk/jwm-menu.cxx.o
.PHONY : fltk/jwm-menu.o

# target to build an object file
fltk/jwm-menu.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-menu.cxx.o
.PHONY : fltk/jwm-menu.cxx.o

fltk/jwm-menu.i: fltk/jwm-menu.cxx.i
.PHONY : fltk/jwm-menu.i

# target to preprocess a source file
fltk/jwm-menu.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-menu.cxx.i
.PHONY : fltk/jwm-menu.cxx.i

fltk/jwm-menu.s: fltk/jwm-menu.cxx.s
.PHONY : fltk/jwm-menu.s

# target to generate assembly for a file
fltk/jwm-menu.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-menu.cxx.s
.PHONY : fltk/jwm-menu.cxx.s

fltk/jwm-mouse.o: fltk/jwm-mouse.cxx.o
.PHONY : fltk/jwm-mouse.o

# target to build an object file
fltk/jwm-mouse.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-mouse.cxx.o
.PHONY : fltk/jwm-mouse.cxx.o

fltk/jwm-mouse.i: fltk/jwm-mouse.cxx.i
.PHONY : fltk/jwm-mouse.i

# target to preprocess a source file
fltk/jwm-mouse.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-mouse.cxx.i
.PHONY : fltk/jwm-mouse.cxx.i

fltk/jwm-mouse.s: fltk/jwm-mouse.cxx.s
.PHONY : fltk/jwm-mouse.s

# target to generate assembly for a file
fltk/jwm-mouse.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-mouse.cxx.s
.PHONY : fltk/jwm-mouse.cxx.s

fltk/jwm-panel.o: fltk/jwm-panel.cxx.o
.PHONY : fltk/jwm-panel.o

# target to build an object file
fltk/jwm-panel.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-panel.cxx.o
.PHONY : fltk/jwm-panel.cxx.o

fltk/jwm-panel.i: fltk/jwm-panel.cxx.i
.PHONY : fltk/jwm-panel.i

# target to preprocess a source file
fltk/jwm-panel.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-panel.cxx.i
.PHONY : fltk/jwm-panel.cxx.i

fltk/jwm-panel.s: fltk/jwm-panel.cxx.s
.PHONY : fltk/jwm-panel.s

# target to generate assembly for a file
fltk/jwm-panel.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-panel.cxx.s
.PHONY : fltk/jwm-panel.cxx.s

fltk/jwm-settings.o: fltk/jwm-settings.cxx.o
.PHONY : fltk/jwm-settings.o

# target to build an object file
fltk/jwm-settings.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-settings.cxx.o
.PHONY : fltk/jwm-settings.cxx.o

fltk/jwm-settings.i: fltk/jwm-settings.cxx.i
.PHONY : fltk/jwm-settings.i

# target to preprocess a source file
fltk/jwm-settings.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-settings.cxx.i
.PHONY : fltk/jwm-settings.cxx.i

fltk/jwm-settings.s: fltk/jwm-settings.cxx.s
.PHONY : fltk/jwm-settings.s

# target to generate assembly for a file
fltk/jwm-settings.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-settings.cxx.s
.PHONY : fltk/jwm-settings.cxx.s

fltk/jwm-shutdown.o: fltk/jwm-shutdown.cxx.o
.PHONY : fltk/jwm-shutdown.o

# target to build an object file
fltk/jwm-shutdown.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-shutdown.cxx.o
.PHONY : fltk/jwm-shutdown.cxx.o

fltk/jwm-shutdown.i: fltk/jwm-shutdown.cxx.i
.PHONY : fltk/jwm-shutdown.i

# target to preprocess a source file
fltk/jwm-shutdown.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-shutdown.cxx.i
.PHONY : fltk/jwm-shutdown.cxx.i

fltk/jwm-shutdown.s: fltk/jwm-shutdown.cxx.s
.PHONY : fltk/jwm-shutdown.s

# target to generate assembly for a file
fltk/jwm-shutdown.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-shutdown.cxx.s
.PHONY : fltk/jwm-shutdown.cxx.s

fltk/jwm-themes.o: fltk/jwm-themes.cxx.o
.PHONY : fltk/jwm-themes.o

# target to build an object file
fltk/jwm-themes.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-themes.cxx.o
.PHONY : fltk/jwm-themes.cxx.o

fltk/jwm-themes.i: fltk/jwm-themes.cxx.i
.PHONY : fltk/jwm-themes.i

# target to preprocess a source file
fltk/jwm-themes.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-themes.cxx.i
.PHONY : fltk/jwm-themes.cxx.i

fltk/jwm-themes.s: fltk/jwm-themes.cxx.s
.PHONY : fltk/jwm-themes.s

# target to generate assembly for a file
fltk/jwm-themes.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-themes.cxx.s
.PHONY : fltk/jwm-themes.cxx.s

fltk/jwm-window.o: fltk/jwm-window.cxx.o
.PHONY : fltk/jwm-window.o

# target to build an object file
fltk/jwm-window.cxx.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-window.cxx.o
.PHONY : fltk/jwm-window.cxx.o

fltk/jwm-window.i: fltk/jwm-window.cxx.i
.PHONY : fltk/jwm-window.i

# target to preprocess a source file
fltk/jwm-window.cxx.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-window.cxx.i
.PHONY : fltk/jwm-window.cxx.i

fltk/jwm-window.s: fltk/jwm-window.cxx.s
.PHONY : fltk/jwm-window.s

# target to generate assembly for a file
fltk/jwm-window.cxx.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/fltk/jwm-window.cxx.s
.PHONY : fltk/jwm-window.cxx.s

src/Apps.o: src/Apps.cpp.o
.PHONY : src/Apps.o

# target to build an object file
src/Apps.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/Apps.cpp.o
.PHONY : src/Apps.cpp.o

src/Apps.i: src/Apps.cpp.i
.PHONY : src/Apps.i

# target to preprocess a source file
src/Apps.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/Apps.cpp.i
.PHONY : src/Apps.cpp.i

src/Apps.s: src/Apps.cpp.s
.PHONY : src/Apps.s

# target to generate assembly for a file
src/Apps.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/Apps.cpp.s
.PHONY : src/Apps.cpp.s

src/Config.o: src/Config.cpp.o
.PHONY : src/Config.o

# target to build an object file
src/Config.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/Config.cpp.o
.PHONY : src/Config.cpp.o

src/Config.i: src/Config.cpp.i
.PHONY : src/Config.i

# target to preprocess a source file
src/Config.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/Config.cpp.i
.PHONY : src/Config.cpp.i

src/Config.s: src/Config.cpp.s
.PHONY : src/Config.s

# target to generate assembly for a file
src/Config.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/Config.cpp.s
.PHONY : src/Config.cpp.s

src/flAutostart.o: src/flAutostart.cpp.o
.PHONY : src/flAutostart.o

# target to build an object file
src/flAutostart.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flAutostart.cpp.o
.PHONY : src/flAutostart.cpp.o

src/flAutostart.i: src/flAutostart.cpp.i
.PHONY : src/flAutostart.i

# target to preprocess a source file
src/flAutostart.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flAutostart.cpp.i
.PHONY : src/flAutostart.cpp.i

src/flAutostart.s: src/flAutostart.cpp.s
.PHONY : src/flAutostart.s

# target to generate assembly for a file
src/flAutostart.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flAutostart.cpp.s
.PHONY : src/flAutostart.cpp.s

src/flDesktop.o: src/flDesktop.cpp.o
.PHONY : src/flDesktop.o

# target to build an object file
src/flDesktop.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flDesktop.cpp.o
.PHONY : src/flDesktop.cpp.o

src/flDesktop.i: src/flDesktop.cpp.i
.PHONY : src/flDesktop.i

# target to preprocess a source file
src/flDesktop.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flDesktop.cpp.i
.PHONY : src/flDesktop.cpp.i

src/flDesktop.s: src/flDesktop.cpp.s
.PHONY : src/flDesktop.s

# target to generate assembly for a file
src/flDesktop.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flDesktop.cpp.s
.PHONY : src/flDesktop.cpp.s

src/flFont.o: src/flFont.cpp.o
.PHONY : src/flFont.o

# target to build an object file
src/flFont.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flFont.cpp.o
.PHONY : src/flFont.cpp.o

src/flFont.i: src/flFont.cpp.i
.PHONY : src/flFont.i

# target to preprocess a source file
src/flFont.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flFont.cpp.i
.PHONY : src/flFont.cpp.i

src/flFont.s: src/flFont.cpp.s
.PHONY : src/flFont.s

# target to generate assembly for a file
src/flFont.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flFont.cpp.s
.PHONY : src/flFont.cpp.s

src/flIcons.o: src/flIcons.cpp.o
.PHONY : src/flIcons.o

# target to build an object file
src/flIcons.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flIcons.cpp.o
.PHONY : src/flIcons.cpp.o

src/flIcons.i: src/flIcons.cpp.i
.PHONY : src/flIcons.i

# target to preprocess a source file
src/flIcons.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flIcons.cpp.i
.PHONY : src/flIcons.cpp.i

src/flIcons.s: src/flIcons.cpp.s
.PHONY : src/flIcons.s

# target to generate assembly for a file
src/flIcons.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flIcons.cpp.s
.PHONY : src/flIcons.cpp.s

src/flKeyboard.o: src/flKeyboard.cpp.o
.PHONY : src/flKeyboard.o

# target to build an object file
src/flKeyboard.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flKeyboard.cpp.o
.PHONY : src/flKeyboard.cpp.o

src/flKeyboard.i: src/flKeyboard.cpp.i
.PHONY : src/flKeyboard.i

# target to preprocess a source file
src/flKeyboard.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flKeyboard.cpp.i
.PHONY : src/flKeyboard.cpp.i

src/flKeyboard.s: src/flKeyboard.cpp.s
.PHONY : src/flKeyboard.s

# target to generate assembly for a file
src/flKeyboard.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flKeyboard.cpp.s
.PHONY : src/flKeyboard.cpp.s

src/flMouse.o: src/flMouse.cpp.o
.PHONY : src/flMouse.o

# target to build an object file
src/flMouse.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flMouse.cpp.o
.PHONY : src/flMouse.cpp.o

src/flMouse.i: src/flMouse.cpp.i
.PHONY : src/flMouse.i

# target to preprocess a source file
src/flMouse.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flMouse.cpp.i
.PHONY : src/flMouse.cpp.i

src/flMouse.s: src/flMouse.cpp.s
.PHONY : src/flMouse.s

# target to generate assembly for a file
src/flMouse.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flMouse.cpp.s
.PHONY : src/flMouse.cpp.s

src/flPanel.o: src/flPanel.cpp.o
.PHONY : src/flPanel.o

# target to build an object file
src/flPanel.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flPanel.cpp.o
.PHONY : src/flPanel.cpp.o

src/flPanel.i: src/flPanel.cpp.i
.PHONY : src/flPanel.i

# target to preprocess a source file
src/flPanel.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flPanel.cpp.i
.PHONY : src/flPanel.cpp.i

src/flPanel.s: src/flPanel.cpp.s
.PHONY : src/flPanel.s

# target to generate assembly for a file
src/flPanel.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flPanel.cpp.s
.PHONY : src/flPanel.cpp.s

src/flThemes.o: src/flThemes.cpp.o
.PHONY : src/flThemes.o

# target to build an object file
src/flThemes.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flThemes.cpp.o
.PHONY : src/flThemes.cpp.o

src/flThemes.i: src/flThemes.cpp.i
.PHONY : src/flThemes.i

# target to preprocess a source file
src/flThemes.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flThemes.cpp.i
.PHONY : src/flThemes.cpp.i

src/flThemes.s: src/flThemes.cpp.s
.PHONY : src/flThemes.s

# target to generate assembly for a file
src/flThemes.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flThemes.cpp.s
.PHONY : src/flThemes.cpp.s

src/flWindow.o: src/flWindow.cpp.o
.PHONY : src/flWindow.o

# target to build an object file
src/flWindow.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flWindow.cpp.o
.PHONY : src/flWindow.cpp.o

src/flWindow.i: src/flWindow.cpp.i
.PHONY : src/flWindow.i

# target to preprocess a source file
src/flWindow.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flWindow.cpp.i
.PHONY : src/flWindow.cpp.i

src/flWindow.s: src/flWindow.cpp.s
.PHONY : src/flWindow.s

# target to generate assembly for a file
src/flWindow.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/flWindow.cpp.s
.PHONY : src/flWindow.cpp.s

src/jwm.o: src/jwm.cpp.o
.PHONY : src/jwm.o

# target to build an object file
src/jwm.cpp.o:
	$(MAKE) -f CMakeFiles/jwm-settings-manager.dir/build.make CMakeFiles/jwm-settings-manager.dir/src/jwm.cpp.o
.PHONY : src/jwm.cpp.o

src/jwm.i: src/jwm.cpp.i
.PHONY : src/jwm.i

# target to preprocess a source file
src/jwm.cpp.i:
	$(MAKE) -f CMakeFiles/jwm-settings-manager.dir/build.make CMakeFiles/jwm-settings-manager.dir/src/jwm.cpp.i
.PHONY : src/jwm.cpp.i

src/jwm.s: src/jwm.cpp.s
.PHONY : src/jwm.s

# target to generate assembly for a file
src/jwm.cpp.s:
	$(MAKE) -f CMakeFiles/jwm-settings-manager.dir/build.make CMakeFiles/jwm-settings-manager.dir/src/jwm.cpp.s
.PHONY : src/jwm.cpp.s

src/tinyxml2.o: src/tinyxml2.cpp.o
.PHONY : src/tinyxml2.o

# target to build an object file
src/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/tinyxml2.cpp.o
.PHONY : src/tinyxml2.cpp.o

src/tinyxml2.i: src/tinyxml2.cpp.i
.PHONY : src/tinyxml2.i

# target to preprocess a source file
src/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/tinyxml2.cpp.i
.PHONY : src/tinyxml2.cpp.i

src/tinyxml2.s: src/tinyxml2.cpp.s
.PHONY : src/tinyxml2.s

# target to generate assembly for a file
src/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/tinyxml2.cpp.s
.PHONY : src/tinyxml2.cpp.s

src/ui.o: src/ui.cpp.o
.PHONY : src/ui.o

# target to build an object file
src/ui.cpp.o:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/ui.cpp.o
.PHONY : src/ui.cpp.o

src/ui.i: src/ui.cpp.i
.PHONY : src/ui.i

# target to preprocess a source file
src/ui.cpp.i:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/ui.cpp.i
.PHONY : src/ui.cpp.i

src/ui.s: src/ui.cpp.s
.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.cpp.s:
	$(MAKE) -f CMakeFiles/JSM.dir/build.make CMakeFiles/JSM.dir/src/ui.cpp.s
.PHONY : src/ui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... JSM"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... jwm-settings-manager"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... fltk/jwm-autostart.o"
	@echo "... fltk/jwm-autostart.i"
	@echo "... fltk/jwm-autostart.s"
	@echo "... fltk/jwm-desktop.o"
	@echo "... fltk/jwm-desktop.i"
	@echo "... fltk/jwm-desktop.s"
	@echo "... fltk/jwm-fonts.o"
	@echo "... fltk/jwm-fonts.i"
	@echo "... fltk/jwm-fonts.s"
	@echo "... fltk/jwm-icons.o"
	@echo "... fltk/jwm-icons.i"
	@echo "... fltk/jwm-icons.s"
	@echo "... fltk/jwm-keyboard.o"
	@echo "... fltk/jwm-keyboard.i"
	@echo "... fltk/jwm-keyboard.s"
	@echo "... fltk/jwm-menu.o"
	@echo "... fltk/jwm-menu.i"
	@echo "... fltk/jwm-menu.s"
	@echo "... fltk/jwm-mouse.o"
	@echo "... fltk/jwm-mouse.i"
	@echo "... fltk/jwm-mouse.s"
	@echo "... fltk/jwm-panel.o"
	@echo "... fltk/jwm-panel.i"
	@echo "... fltk/jwm-panel.s"
	@echo "... fltk/jwm-settings.o"
	@echo "... fltk/jwm-settings.i"
	@echo "... fltk/jwm-settings.s"
	@echo "... fltk/jwm-shutdown.o"
	@echo "... fltk/jwm-shutdown.i"
	@echo "... fltk/jwm-shutdown.s"
	@echo "... fltk/jwm-themes.o"
	@echo "... fltk/jwm-themes.i"
	@echo "... fltk/jwm-themes.s"
	@echo "... fltk/jwm-window.o"
	@echo "... fltk/jwm-window.i"
	@echo "... fltk/jwm-window.s"
	@echo "... src/Apps.o"
	@echo "... src/Apps.i"
	@echo "... src/Apps.s"
	@echo "... src/Config.o"
	@echo "... src/Config.i"
	@echo "... src/Config.s"
	@echo "... src/flAutostart.o"
	@echo "... src/flAutostart.i"
	@echo "... src/flAutostart.s"
	@echo "... src/flDesktop.o"
	@echo "... src/flDesktop.i"
	@echo "... src/flDesktop.s"
	@echo "... src/flFont.o"
	@echo "... src/flFont.i"
	@echo "... src/flFont.s"
	@echo "... src/flIcons.o"
	@echo "... src/flIcons.i"
	@echo "... src/flIcons.s"
	@echo "... src/flKeyboard.o"
	@echo "... src/flKeyboard.i"
	@echo "... src/flKeyboard.s"
	@echo "... src/flMouse.o"
	@echo "... src/flMouse.i"
	@echo "... src/flMouse.s"
	@echo "... src/flPanel.o"
	@echo "... src/flPanel.i"
	@echo "... src/flPanel.s"
	@echo "... src/flThemes.o"
	@echo "... src/flThemes.i"
	@echo "... src/flThemes.s"
	@echo "... src/flWindow.o"
	@echo "... src/flWindow.i"
	@echo "... src/flWindow.s"
	@echo "... src/jwm.o"
	@echo "... src/jwm.i"
	@echo "... src/jwm.s"
	@echo "... src/tinyxml2.o"
	@echo "... src/tinyxml2.i"
	@echo "... src/tinyxml2.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

