#!/bin/bash
case "$1" in
    configure)
     directory="/etc/menu-methods"
     bin_list=(jwm-placesmenu jwm-desktopmenu)
     PROGNAME="${0/*\/}"
     ## our startup log file
     LOGDIR="$HOME/.jwm/jsm-logs"
     if [[ ! -d "$HOME" ]]
     then
       if [[ -d "/var/log" ]]
       then
         LOGDIR="/var/log"
       else
         LOGDIR="/"
       fi
     fi
     [[ -d "$LOGDIR" ]] || mkdir -p "$LOGDIR" 2> /dev/null
     chmod -R a+rw "${LOGDIR}" 2> /dev/null
     LOG="$LOGDIR/$PROGNAME.log"
     date -I >"$LOG"
     LOG(){
       echo "$*" >> "$LOG" 2> /dev/null
     }
     ## make our menu-methods executables
     for app in "${bin_list[@]}"
     do
       [[ -f "${directory}${app}" ]] && [[ ! -x "${directory}${app}" ]] && chmod +x "${directory}${app}"
     done
     RECONF="$(which reconfigure_jwm_themes)"
     if [[ -n "$RECONF" ]]
     then
        [[ ! -x "$RECONF" ]] && chmod +x "$RECONF"
        $RECONF
     else
       echo "jwm theme reconfiguration program is not present"
     fi
	;;

    abort-upgrade|abort-deconfigure|abort-remove)
	;;

    *)
	echo "$0 called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac
#DEBHELPER#
exit 0
