#!/bin/bash
gettext(){
	printf "%s" "$*"
}
source gettext.sh
export TEXTDOMAIN=jwm-settings-manager
#####################################################################################
## Places Menu
PLACES_NAME=$(gettext "Places")
## Applications menu
MENU_NAME=$(gettext "Apps")
SHUTDOWN_NAME=$(gettext "Shutdown")
Help=$(gettext "Help")
Calendar=$(gettext "Calendar")
## This menu item refreshes/reloads the window manager
ReloadDesktop=$(gettext "Reload Desktop")
ClockSettings=$(gettext "Clock Settings")
## this opens the home folder
Home=$(gettext "Home")
TimezoneSettings=$(gettext "Timezone")
## This is the general settings
Settings=$(gettext "Settings")
EditPanel=$(gettext "Edit Panel")
ChangeDesktopBackground=$(gettext "Change Desktop Background")
AboutToriOS=$(gettext "About ToriOS")
AboutUs=$(gettext "About Us")
SoftwareInstaller=$(gettext "Software Installer")
## this is to run a program
Run=$(gettext "Run")
## This is to locate a file
Locate=$(gettext "Locate")
UPDATE_SYS=$(gettext "Update System")
## Software packages, or programs
INSTALL_PKGS=$(gettext "Install Packages")
INFO=$(gettext "Information")
ABOUT_SOFT_INST=$(gettext "About Software installer")
## Software packages, or programs
LIST_BROKEN=$(gettext "List All Installed Packages")
## Software packages, or programs
FIX_BROKEN=$(gettext "Fix broken packages")
## Add an icon to the desktop
ADD_NEW=$(gettext "Add new items to Desktop")
#####################################################################################
##TODO: fix this so the install dir can be changed via the user
RELINSTDIR="/usr/share"
PROGNAME="${0/*\/}"
if [[ "$(whoami)" != "root" ]]
then
  echo "Please rerun $0 as root"
  exit 0
fi
myTTY="$XDG_VTNR"
if [[ -n "$myTTY" ]]
then
  myTTY="tty$myTTY"
else
  myTTY="tty7"
fi
## get the user name through some really nifty testing    
if [[ -n "$SUDO_USER" ]]
then
   [[ -n "$DISPLAY" ]] && [[ -z "$postintME" ]] && postintME=$(last -wR |grep "$myTTY"| grep "still logged in" | sed "s/ .*//")
   [[ -n "$DISPLAY" ]] && [[ -z "$postintME" ]] &&postintME=$(last -wR |grep -m 1 "$myTTY"|sed "s/ .*//")
[[ -n "$DISPLAY" ]] && [[ -z "$postintME" ]] &&postintME=$(last |grep "$DISPLAY"| grep "still logged in" |sed "s/ .*//")
[[ -n "$DISPLAY" ]] && [[ -z "$postintME" ]] &&postintME=$(last |grep -m 1 "$DISPLAY"|sed "s/ .*//")
  [[ -n "$postintME" ]] &&  postintME="${postintME/$'\n'*}" && echo "User logged in on $myTTY is $postintME.  This will be used to chown files"
else
   postintME="$SUDO_USER"
fi
export postintME
[[ -n "$postintME" ]] && [[ -d "/home/$postintME" ]] && HOMMIE="/home/$postintME"
[[ -z "$postintME" ]] && HOMMIE="$HOME" && postintME=$(whoami)

## our startup log file
LOGDIR="$HOMMIE/.jwm/jsm-logs"
if [[ ! -d "$HOMMIE" ]]
then
   if [[ -d "/var/log" ]]
   then
     LOGDIR="/var/log"
   else
     LOGDIR="/"
   fi
fi
[[ -d "$LOGDIR" ]] || mkdir -p "$LOGDIR" 2> /dev/null
chmod -R a+rw "${LOGDIR}" 2> /dev/null
LOG="$LOGDIR/$PROGNAME.log"
date -I >"$LOG"
LOG(){
    printf "%s\n" "$*" >> "$LOG" 2> /dev/null
}
## program arrays to test to use in the jwmrc files
BATTprogs=(xfce4-power-manager batteri)
TERMS=(sakura lxterminal gnome-terminal xfce4-terminal xterm roxterm mrxvt rxvt)
WEBLIST=(firefox chromium chrome qupzilla palemoon midori opera elinks dillo links2)
SYS_MONITORS=(xfce4-task-manager htop atop top gnome-system-monitor)
DESKTOPprogS=(rox nautilus)
FMprogs=(thunar rox spacefm xfe caja nautilus dolphin doublecmd-gtk emelfm2 gentoo gnome-commander mc nemo tuxcmd worker xfm)
screenieProgs=(scrot import screengrab shutter xfce4-screenshooter gnome-screenshot)
calcProgs=(calcoo galculator gnome-calculator kcalc qalculate-gtk wmcalc)
runProgs=(grun)
searchProgs=(catfish)
displayProgs=(lxrandr gvidm gddccontrol)
helpProgs=(gman yelp)
calendarProgs=(zenity yad ccal evolution gdeskcal gsimplecal gnome-calendar osmo orage python-goocalendar remind when wmdate xcal)
clockProgs=(sunclock gworldclock)
STARTvolS=(volumeicon)
toriOSrunCheck="$(which torios-runchecker) "
FONT="serif" ##TODO find system font and use it...
JWMver=$(jwm -v)
JWMmajor="${JWMver/JWM v}"
JWMmajor="${JWMmajor/ *}"
JWMver="${JWMmajor}"
MINOR="${JWMmajor/*.}"
MID="${JWMmajor/.$MINOR}"
MID="${MID/*.}"
JWMmajor="${JWMmajor/.*}"
JWMmajor=$(( JWMmajor ))
MID=$(( MID ))
MINOR=$(( MINOR ))
if (( MID >= 3 ))
then
  JWMver="new"
elif (( MID <3 )) && (( MINOR > 1 ))
then
  JWMver="mid"
elif [ "${JWMver/}" ]
then
  JWMver="old"
else
  echo "JWM version is found as $JWMver"
fi

Gbg=$(gsettings get org.gnome.desktop.background picture-uri)
Gbg="${Gbg//\'}"
Gbg="${Gbg/file:\/\/}"
BG_LIST=("$Gbg")
isImage(){
  file="$1"
  [[ ! -f $file ]] && return 1
  formats=("png" "svg" "jpg" "jpeg" "gif")
  for fmt in "${formats[@]}"
  do
    tmpimg="${file,,}"
     if [[ "${tmpimg%$fmt}" != "$tmpimg" ]]
     then
       echo "$file"
       return 0
     fi
  done
}
for image in /usr/share/backgrounds/**
do
  [[ -n $(isImage "$image") ]] && BG_LIST=(${BG_LIST[@]} "$image")
done
for image in /usr/share/images/desktop-base/**
do
  [[ -n $(isImage "$image") ]] && BG_LIST=(${BG_LIST[@]} "$image")
done
iconDIRS=("\$HOME/.local/share/icons/" "\$HOME/.local/share/icons/hicolor" "\$HOME/.local/share/icons/hicolor/128x128" "\$HOME/.local/share/icons/hicolor/128x128/apps" "\$HOME/.local/share/icons/hicolor/16x16" "\$HOME/.local/share/icons/hicolor/16x16/apps" "\$HOME/.local/share/icons/hicolor/24x24" "\$HOME/.local/share/icons/hicolor/24x24/apps" "\$HOME/.local/share/icons/hicolor/256x256" "\$HOME/.local/share/icons/hicolor/256x256/apps" "\$HOME/.local/share/icons/hicolor/32x32")
FONT="${FONT}-12:antialias=true:encoding=utf8"
EXEC="jwm-settings-manager"
[[ -z "$RELINSTDIR" ]] && RELINSTDIR="/usr/share/"
INSTDIR="$RELINSTDIR/$EXEC"
## DEFAULT PROGRAMS
EXTENTION=".svg"

JSM="jwm-settings-manager"
JWMexec="exec:"
TORIGAMMA="$(which torios-gamma)"
if [ -n "$TORIGAMMA" ]
then
  brightUP="$TORIGAMMA up"
  brightDown="$TORIGAMMA down"
fi
getPROG(){
  EXEC="$1"
  shift
  LIST=(${@})
  if [[ ! -x "$(which $EXEC)" ]]
  then
    PROG=""
	[[ -z "${LIST[@]}" ]] && echo "" && return
    for i in "${LIST[@]}"
    do
      [[ -x "$(which $i)" ]] && PROG="$i" && LOG "getPROG Found: $PROG" && echo "$PROG" && break
    done
  else
    LOG "getPROG unsing first item: $PROG"
    PROG="$EXEC"
    echo "$PROG"
  fi
  
}
WEB_PROG=$(getPROG "x-www-browser" "${WEBLIST[@]}")
TERM_PROG=$(getPROG "x-terminal-emulator" "${TERMS[@]}")
[[ -n $TERM_PROG ]] && LOG "TERM_PROG=$TERM_PROG"
SYS_MONITOR=$(getPROG "lxtask" "${SYS_MONITORS[@]}")
[[ -n "$SYS_MONITOR" ]] && LOG "System Monitor=$SYS_MONITOR"
case $SYS_MONITOR in
  top|htop)SYS_MONITOR="$TERM_PROG -e $SYS_MONITOR";;
  *);;
esac
STARTvol=$(getPROG "torios-volume" "${STARTvolS[@]}")
[[ -n $STARTvol ]] && LOG "STARTvol=$STARTvol"
##Startup commands
DESKTOPprog=$(getPROG "pcmanfm" "${DESKTOPprogS[@]}")
[[ -n $DESKTOPprog ]] && LOG "DESKTOPprog=$DESKTOPprog"
case $DESKTOPprog in
  rox) DESKTOPprog="$DESKTOPprog -p";;
  pcmanfm)DESKTOPprog="$DESKTOPprog --desktop";;
  *);;
esac
[[ -n "$DESKTOPprog" ]] && STARTUP="<StartupCommand>$DESKTOPprog</StartupCommand>"
[[ -n "$STARTvol" ]] && STARTUP="$STARTUP
   <StartupCommand>$STARTvol</StartupCommand>"
FM_PROG=$(getPROG "pcmanfm" "${FMprogs[@]}")
BATTprog=$(getPROG "torios-battery" "${BATTprogs[@]}")
SCREEN_SHOT=$(getPROG "screenie" "${screenieProgs[@]}")
RUN_DIALOG=$(getPROG "zrun" "${runProgs[@]}")
CALC_PROG=$(getPROG "xcalc" "${calcProgs[@]}")
VOL_UP="amixer-up"
[[ -x "$VOL_UP" ]] || VOL_UP=""
VOL_DOWN="amixer-down"
[[ -x "$VOL_DOWN" ]] || VOL_DOWN=""
VOL_MUTE="amixer-toggle"
[[ -x "$VOL_MUTE" ]] || VOL_MUTE=""
HELP_PROG=$(getPROG "xman" "${helpProgs[@]}")
DISPLAY_PROG=$(getPROG "arandr" "${displayProgs[@]}")
LOGOUT_PROGRAM="torios-exit"
[[ -x "$LOGOUT_PROGRAM" ]] || LOGOUT_PROGRAM="jwm -ext"
TZ_PROG=$(getPROG "dpkg-reconfigure" "${clockProgs[@]}")
[[ $TZ_PROG == "dpkg-reconfigure" ]] && TZ_PROG="xterm -e 'sudo dpkg-reconfigure tzdata'"
CAL_PROG=$(getPROG "torios-calendar" "${calendarProgs[@]}")
[[ -n $CAL_PROG ]] && LOG "CAL_PROG=$CAL_PROG"
case $CAL_PROG in
  zenity|yad)CAL_PROG="$CAL_PROG --calendar";;
  *);;
esac
SEARCH_PROG=$(getPROG "zlocate" "${searchProgs[@]}")
[[ -n $SEARCH_PROG ]] && LOG "SEARCH_PROG=$SEARCH_PROG"
RESTART_PROGRAM=$(getPROG "torios-reboot" "$JSM")
[[ -n $(which "$RESTART_PROGRAM") ]] || RESTART_PROGRAM=""
[[ "$RESTART_PROGRAM" == "$JSM" ]] && RESTART_PROGRAM="$JSM --halt"
## menu programs
PLACES_INCLUDE=$(getPROG "jwm-places" "jwm-places-bash")
if [[ -z "$(which $PLACES_INCLUDE)" ]]
then
  PLACES_INCLUDE=""
fi
JWM_MENU=$(getPROG "jwm-menu" "jwm-menu-bash")
if [[ -z "$(which $JWM_MENU)" ]]
then
  JWM_MENU=""
fi

## help programs
ABOUT_PROG="torios-about || ${WEB_PROG} http://torios.top"
MANUAL="${WEB_PROG} /usr/share/doc/torios/html/index.html"
STARTPAGE="${WEB_PROG} /usr/share/doc/torios/startpage.html"

# Web pages
FACEB="https://www.facebook.com/ToriOS.Official"
GPLUS="https://plus.google.com/113578220061772446187/posts"
TWITTER="https://twitter.com/ToriOS_Official"
LP="https://launchpad.net/~torios"

## Startup
	STARTUP="$STARTUP
  <StartupCommand>\$HOME/.config/jsm-mouse</StartupCommand>"
[[ -x "nice-start" ]] && STARTUP="$STARTUP
   <StartupCommand>nice-start</StartupCommand>"
## Desktop Background
BG="/usr/share/backgrounds/default.jpg"
if [ ! -f "$BG" ]
then
  BG=""
  for i in "${BG_LIST[@]}"
  do
     [[ -z "$MYBG" ]] && [[ -f "$i" ]] && MYBG="$i"
  done
  [[ -n "$MYBG" ]] && BG="$MYBG"
fi
[[ -n "$BG" ]] && LOG "BG=$BG"
STARTPAGE_ICON="browser${EXTENTION}"
################### MENUS ###############################
if [[ -n $(which torios-installer) ]]
then
  TRAYbuttonForTray="        <TrayButton popup=\"$SoftwareInstaller\" icon=\"software-center\" border=\"false\">
          <Button mask=\"123\">exec:torios-installer --search</Button>
          <Button mask=\"23\">root:j</Button>
        </TrayButton>
"
  INTSTALLER_MENU="	<RootMenu height=\"16\" onroot=\"j\">
		<Program icon=\"system-software-update\" label=\"$UPDATE_SYS\">torios-installer --update</Program>
		<Program icon=\"software-center\" label=\"$INSTALL_PKGS\">torios-installer --search</Program>
		<Program icon=\"system-software-update\" label=\"$INFO\">torios-installer --info</Program>
		<Program icon=\"gtk-about\" label=\"$ABOUT_SOFT_INST\">torios-installer --about</Program>
		<Program icon=\"gtk-info\" label=\"$LIST_BROKEN\">torios-installer --list</Program>
		<Program icon=\"system-error\" label=\"$FIX_BROKEN\">torios-installer --fix</Program>
	</RootMenu>"
fi
if [[ -n $(which zrun) ]]
then
TRAYbuttonForTray="$TRAYbuttonForTray        <TrayButton popup=\"$Locate\" icon=\"system-search\" border=\"false\">
          <Button mask=\"123\">exec:zlocate</Button>
        </TrayButton>
"
fi
if [[ -n $(which zlocate) ]]
then
TRAYbuttonForTray="$TRAYbuttonForTray        <TrayButton popup=\"$Run\" icon=\"system-run\" border=\"false\">
          <Button mask=\"123\">exec:zrun</Button>
        </TrayButton>
"
fi
## CLOCK
CLOCK_FORMAT="%a, %e %b %l:%M %p"
CLOCK="root:c"
OLD_CLOCK="${CAL_PROG}"
OLD_CLOCK_TAG="<Clock format=\"${CLOCK_FORMAT}\">${OLD_CLOCK}</Clock>"
CLOCK_TAG="<Clock format=\"${CLOCK_FORMAT}\">${CLOCK}</Clock>"
CLOCK_MENU="<!-- Clock Menu-->
    <RootMenu height=\"0\" onroot=\"c\">
        <Program icon=\"time${EXTENTION}\" label=\"$ClockSettings\">${JSM} --clock-settings</Program>
         <Separator/>
        <Program icon=\"calendar${EXTENTION}\" label=\"$Calendar\">${OLD_CLOCK}</Program>
        <Program icon=\"time${EXTENTION}\" label=\"$TimezoneSettings\">${TZ_PROG}</Program>
    </RootMenu>"

## Panel Edit
EDIT_PANEL_ROOT="root:p"
EDIT_PANEL="    <RootMenu onroot=\"p\">
	<Program icon=\"jsm-panel${EXTENTION}\" label=\"$EditPanel\">${JSM} --panel</Program>
	<Program icon=\"add${EXTENTION}\" label=\"Add new items\">${JSM} --shortcuts</Program>
    </RootMenu>"

## Menu Edit
EDIT_MENU_ROOT="root:m"
EDIT_MENU="    <RootMenu onroot=\"m\">
	<Program icon=\"reload${EXTENTION}\" label=\"Update Menus\">update-menus</Program>
	<Program icon=\"jsm-panel${EXTENTION}\" label=\"Edit Menu\">${JSM} --menu</Program>
	<Program icon=\"jsm-panel${EXTENTION}\" label=\"Edit Panel\">${JSM} --panel</Program>
    </RootMenu>"
## SHUTDOWN MENU
SHUTDOWN_ROOT="root:9"

SHUTDOWN_ICON="system-shutdown${EXTENTION}"
SHUTDOWN_PROGRAM="${JSM} --halt"
LOGOUT_ICON="system-logout${EXTENTION}"
RESTART_ICON="system-restart${EXTENTION}"
SHUTERDOWN="<Separator/>
	<Restart label=\"$ReloadDesktop\" icon=\"${RESTART_ICON}\"/>
	<Program icon=\"${SHUTDOWN_ICON}\" label=\"$SHUTDOWN_NAME\">${SHUTDOWN_PROGRAM}</Program>"

## MAIN MENU
JWM_ROOT_NUM="2"
JWM_ROOT="root:${JWM_ROOT_NUM}"
if [ -n "$(which starttorios)" ]
then
  JWM_ROOT_MENU="<RootMenu onroot=\"${JWM_ROOT_NUM}\">"
  [[ -n "$JWM_MENU" ]] && JWM_ROOT_MENU="$JWM_ROOT_MENU
       <Include>${JWMexec}${JWM_MENU}</Include>"
  JWM_ROOT_MENU="$JWM_ROOT_MENU
       <Menu label=\"$AboutToriOS\" icon=\"help-about${EXTENTION}\" height=\"0\">
           <Program label=\"$Help\" icon=\"help${EXTENTION}\">${MANUAL}</Program>
           <Program label=\"Launchpad\" icon=\"launchpad${EXTENTION}\">${WEB_PROG} ${LP}</Program>
           <Program label=\"G+\" icon=\"googleplus${EXTENTION}\">${WEB_PROG} ${GPLUS}</Program>
           <Program label=\"Facebook\" icon=\"facebook${EXTENTION}\">${WEB_PROG} ${FACEB}</Program>
           <Program label=\"Twitter\" icon=\"twitter${EXTENTION}\">${WEB_PROG} ${TWITTER}</Program>
           <Program label=\"$AboutUs\" icon=\"${MENU_ICON}\">${ABOUT_PROG}</Program>
        </Menu>
        ${SHUTERDOWN}
    </RootMenu>"
else
  JWM_ROOT_MENU="<RootMenu onroot=\"${JWM_ROOT_NUM}\">"
[[ -n "$JWM_MENU" ]] && JWM_ROOT_MENU="$JWM_ROOT_MENU
        <Include>${JWMexec}${JWM_MENU}</Include>"
JWM_ROOT_MENU="$JWM_ROOT_MENU        ${SHUTERDOWN}
    </RootMenu>"
fi


MENU_ICON="/usr/share/pixmaps/distributor-logo.png"
if [ ! -f "$MENU_ICON" ]
then
  MENU_ICON="/usr/share/icons/hicolor/48x48/apps/distributor-logo.png"
  if [ ! -f "$MENU_ICON" ]
  then
    MENU_ICON="distributor-logo"
  fi
fi
#MAIN MENU GENERATOR


TORI_ROOT="${JWM_ROOT}"
## PLACES MENU
PLACES_NUM="7"
PLACES_ROOT="root:${PLACES_NUM}"

PLACES_ICON="folder${EXTENTION}"
PLACES_MENU="    <RootMenu onroot=\"${PLACES_NUM}\">
        <Include>${JWMexec}${PLACES_INCLUDE}</Include>
    </RootMenu>"

MENUS_LIST_NEW="${JWM_ROOT_MENU}
${PLACES_MENU}"
ROOT_MENU="root:${JWM_ROOT_NUM}"
REGULAR_MENUS_LIST="$MENUS_LIST_NEW"
## Mouse MENU

MOUSE_MENU="<RootMenu height=\"0\" onroot=\"3\">
        <Program icon=\"folder-home${EXTENTION}\" label=\"$Home\">xdg-open ~/</Program>
        <Program icon=\"${JSM}${EXTENTION}\" label=\"$Settings\">${JSM}</Program>
		<Program icon=\"add${EXTENTION}\" label=\"$ADD_NEW\">desktop-file-editor</Program>
        <Program icon=\"preferences-desktop-wallpaper${EXTENTION}\" label=\"$ChangeDesktopBackground\">${JSM} --desktop</Program>"
if [[ -n "$JWM_MENU" ]] && [[ "$JWMver" == "new" ]]
then
MOUSE_MENU="${MOUSE_MENU}
		<Dynamic label=\"$MENU_NAME\" icon=\"torios-logo\" border=\"false\">${JWMexec}${JWM_MENU}</Dynamic>"
fi
MOUSE_MENU="${MOUSE_MENU}
    </RootMenu>"
if [[ -n "${INTSTALLER_MENU}" ]]
then
MOUSE_MENU="${MOUSE_MENU}
${INTSTALLER_MENU}"
fi
## window corners override in individual files
CORNER="4"
W_HEIGHT="20"
## PANEL CONFIGURATIONS
## THE NORMAL CONFIG used in Default, Ambiance and Live
[[ -n "$MENU_ICON" ]] && MENU_ICONer=" icon=\"${MENU_ICON}\""
DEFAULT_TRAY="    <Tray x=\"0\" y=\"-1\" height=\"34\" valign=\"top\" width=\"0\" halign=\"fixed\" layout=\"horizontal\">
        <TrayButton label=\"${MENU_NAME}\"${MENU_ICONer} border=\"false\">
            <Button mask=\"1\">${JWM_ROOT}</Button>
            <Button mask=\"23\">${EDIT_MENU_ROOT}</Button>
        </TrayButton>
        <TrayButton label=\"${PLACES_NAME}\" icon=\"${PLACES_ICON}\" border=\"false\">
            <Button mask=\"1\">${PLACES_ROOT}</Button>
            <Button mask=\"23\">${EDIT_MENU_ROOT}</Button>
        </TrayButton>
        <TrayButton icon=\"${STARTPAGE_ICON}\" border=\"false\">
            <Button mask=\"1\">${STARTPAGE}</Button>
            <Button mask=\"23\">${EDIT_PANEL_ROOT}</Button>
        </TrayButton>
        <Pager labeled=\"true\"/>
        <TaskList maxwidth=\"256\"/>
        <Dock/>
$TRAYbuttonForTray"
[[ -n "$(which xload)" ]] && DEFAULT_TRAY="${DEFAULT_TRAY}
           <Swallow name=\"xload\" width=\"64\">xload -nolabel -bg DimGrey -fg Grey -hl DarkGrey</Swallow>"
DEFAULT_TRAY="${DEFAULT_TRAY}
           ${CLOCK_TAG}
    </Tray>"
### OLD STYLE 2.2.2 configs
OLD_TRAY="    <Tray x=\"0\" y=\"-1\" height=\"34\" valign=\"top\" width=\"0\" halign=\"fixed\" layout=\"horizontal\">
        <TrayButton label=\"${MENU_NAME}\"${MENU_ICONer} border=\"false\">${TORI_ROOT}</TrayButton>
        <TrayButton label=\"${PLACES_NAME}\" icon=\"${PLACES_ICON}\" border=\"false\">${PLACES_ROOT}</TrayButton>
        <TrayButton icon=\"${STARTPAGE_ICON}\" border=\"false\">${STARTPAGE}</TrayButton>
        <Pager labeled=\"true\"/>
        <TaskList maxwidth=\"256\"/>
        <Dock/>
$TRAYbuttonForTray"
[[ -n "$(which xload)" ]] && TRAY="$TRAY
           <Swallow name=\"xload\" width=\"64\">xload -nolabel -bg DimGrey -fg Grey -hl DarkGrey</Swallow>"
OLD_TRAY="$OLD_TRAY
        ${OLD_CLOCK_TAG}
        <TrayButton label=\"${SHUTDOWN_NAME}\" icon=\"${SHUTDOWN_ICON}\" border=\"false\">${SHUTDOWN_ROOT}</TrayButton>
    </Tray>"
TRAY="${DEFAULT_TRAY}"
## see http://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts
# I tried to implement everything from GNOME, Windows and OSX in here
KEYSHORTCUTS="<Key key=\"Up\">up</Key>
    <Key key=\"Down\">down</Key>
    <Key key=\"Right\">right</Key>
    <Key key=\"Left\">left</Key>
    <Key key=\"a\">left</Key>
    <Key key=\"s\">down</Key>
    <Key key=\"w\">up</Key>
    <Key key=\"d\">right</Key>
    <Key key=\"Return\">select</Key>
    <Key key=\"Escape\">escape</Key>
    <Key mask=\"A\" key=\"Tab\">next</Key>
    <Key mask=\"4\" key=\"Tab\">next</Key>
    <Key mask=\"AS\" key=\"Tab\">nextstacked</Key>
    <Key mask=\"S4\" key=\"Tab\">nextstacked</Key>
    <Key mask=\"SA\" key=\"Tab\">nextstacked</Key>
    <Key mask=\"CA\" key=\"Tab\">nextstacked</Key>
    <Key mask=\"C\" key=\"#\">desktop#</Key>
    <Key mask=\"CA\" key=\"Right\">rdesktop</Key>
    <Key mask=\"CA\" key=\"Left\">ldesktop</Key>
    <Key mask=\"CA\" key=\"Up\">udesktop</Key>
    <Key mask=\"CA\" key=\"Down\">ddesktop</Key>
    <Key mask=\"A\" key=\"space\">window</Key>
    <Key mask=\"A\" key=\"F3\">window</Key>
    <Key key=\"F11\">fullscreen</Key>
    <Key mask=\"C\" key=\"F11\">fullscreen</Key>
    <Key mask=\"CS\" key=\"f\">fullscreen</Key>
    <Key mask=\"4C\" key=\"f\">fullscreen</Key>
    <Key mask=\"A\" key=\"F12\">shade</Key>
    <Key mask=\"SC4\" key=\"Up\">maximize</Key>
    <Key mask=\"4\" key=\"L\">maximize</Key>
    <Key mask=\"A\" key=\"F10\">maximize</Key>
    <Key mask=\"4\" key=\"Down\">minimize</Key>
    <Key mask=\"4\" key=\"m\">minimize</Key>
    <Key mask=\"A\" key=\"F9\">minimize</Key>
    <Key mask=\"4\" key=\"w\">close</Key>
    <Key mask=\"A\" key=\"F4\">close</Key>
	<Key key=\"XF86Tools\">${JWMexec}jwm-settings-manager</Key>
	<Key key=\"XF86Eject\">${JWMexec}eject</Key>"

## DYNAMIC includes of things that exist :)
[[ -n "$FM_PROG" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key key=\"XF86MyComputer\">${JWMexec}$FM_PROG</Key>
    <Key key=\"XF86Explorer\">${JWMexec}${FM_PROG/ *}</Key>"
[[ -n "$(which torios-shutdown)" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key key=\"XF86PowerOff\">${JWMexec}torios-shutdown</Key>"
[[ -n "$SEARCH_PROG" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key key=\"XF86Search\">${JWMexec}$SEARCH_PROG</Key>"
[[ -n "$ROOT_MENU" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key mask=\"C\" key=\"Escape\">${ROOT_MENU}</Key>
    <Key key=\"XF86LaunchA\">${ROOT_MENU}</Key>"
[[ -n $(which amixer-mic-mute) ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
	<Key key=\"XF86AudioMicMute\">exec:amixer-mic-mute</Key>"
[[ -n "$VOL_MUTE" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key key=\"XF86AudioMute\">${JWMexec}${VOL_MUTE}</Key>"
[[ -n "$VOL_UP" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key key=\"XF86AudioRaiseVolume\">${JWMexec}${VOL_UP}</Key>"
[[ -n "$VOL_DOWN" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key key=\"XF86AudioLowerVolume\">${JWMexec}${VOL_DOWN}</Key>"
[[ -n "$WEB_PROG" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key key=\"XF86WWW\">${JWMexec}${WEB_PROG}</Key>
    <Key key=\"XF86HomePage\">${JWMexec}${WEB_PROG}</Key>"
[[ -n "$CALC_PROG" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
   <Key key=\"XF86Calculator\">${JWMexec}$toriOSrunCheck${CALC_PROG}</Key>"
[[ -n "$TORIGAMMA" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key key=\"XF86MonBrightnessUp\">${JWMexec}${brightUP}</Key>
    <Key key=\"XF86MonBrightnessDown\">${JWMexec}${brightDown}</Key>"
[[ -n "$SCREEN_SHOT" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key key=\"Print\">${JWMexec}${SCREEN_SHOT}</Key>
    <Key mask=\"CA\" key=\"p\">${JWMexec}${SCREEN_SHOT}</Key>
    <Key mask=\"S4\" key=\"3\">${JWMexec}${SCREEN_SHOT}</Key>"
[[ -n  "${DISPLAY_PROG}" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key key=\"XF86Display\">${JWMexec}${DISPLAY_PROG}</Key>"
[[ -n "$TERM_PROG" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key mask=\"CA\" key=\"t\">${JWMexec}${TERM_PROG}</Key>"
[[ -n "$SYS_MONITOR" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key mask=\"CS\" key=\"Escape\">${JWMexec}$toriOSrunCheck${SYS_MONITOR}</Key>
    <Key mask=\"A4\" key=\"Escape\">${JWMexec}$toriOSrunCheck${SYS_MONITOR}</Key>
    <Key mask=\"CA\" key=\"Delete\">${JWMexec}$toriOSrunCheck${SYS_MONITOR}</Key>
    <Key mask=\"C\" key=\"Escape\">${JWMexec}$toriOSrunCheck${SYS_MONITOR}</Key>"
[[ -n "$HELP_PROG" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key mask=\"A\" key=\"F1\">${JWMexec}${HELP_PROG}</Key>"
[[ -n "$RUN_DIALOG" ]] && KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key mask=\"A\" key=\"F2\">${JWMexec}${RUN_DIALOG}</Key>
    <Key mask=\"4\" key=\"F2\">${JWMexec}${RUN_DIALOG}</Key>
    <Key mask=\"4\" key=\"space\">${JWMexec}${RUN_DIALOG}</Key>"

NEW_KEYSHORTCUTS="${KEYSHORTCUTS}
    <Key mask=\"C4\" key=\"Up\">maxtop</Key>
    <Key mask=\"C4\" key=\"Left\">maxleft</Key>
    <Key mask=\"C4\" key=\"Right\">maxright</Key>
    <Key mask=\"C4\" key=\"Down\">maxbottom</Key>
    <Key mask=\"C4\" key=\"v\">maxv</Key>
    <Key mask=\"4S\" key=\"Up\">maxv</Key>
    <Key mask=\"C4\" key=\"h\">maxh</Key>
    <Key mask=\"4\" key=\"Right\">sendr</Key>
    <Key mask=\"4\" key=\"Left\">sendl</Key>
    <Key mask=\"4\" key=\"Up\">sendu</Key>
    <Key mask=\"4\" key=\"Down\">sendd</Key>
    <Key mask=\"SCA\" key=\"Right\">sendr</Key>
    <Key mask=\"SCA\" key=\"Left\">sendl</Key>
    <Key mask=\"SCA\" key=\"Up\">sendu</Key>
    <Key mask=\"SCA\" key=\"Down\">sendd</Key>"

if [[ -n $(which jwmIconFinder) ]]
then
  LOG "Generating Icons with jwmIconFinder"
  ICONS_LIST=$(jwmIconFinder -o -s 48)
ICONS_LIST="${ICONS_LIST/<JWM>}"
ICONS_LIST="${ICONS_LIST/<\/JWM>}"
else
  [[ -d "/usr/share/icons/Numix/" ]] && ICONS_LIST="$ICONS_LIST  <IconPath>/usr/share/icons/Numix-Circle/scalable/apps</IconPath>
  <IconPath>/usr/share/icons/Numix-Circle/scalable/apps</IconPath>
  <IconPath>/usr/share/icons/Numix-Circle/scalable/apps</IconPath>"

  [[ -d "/usr/share/icons/gnome/" ]] && ICONS_LIST="$ICONS_LIST
  <IconPath>/usr/share/icons/gnome/256x256/actions</IconPath>
  <IconPath>/usr/share/icons/gnome/256x256/apps</IconPath>
  <IconPath>/usr/share/icons/gnome/256x256/categories</IconPath>
  <IconPath>/usr/share/icons/gnome/256x256/devices</IconPath>
  <IconPath>/usr/share/icons/gnome/256x256/emblems</IconPath>
  <IconPath>/usr/share/icons/gnome/256x256/mimetypes</IconPath>
  <IconPath>/usr/share/icons/gnome/256x256/places</IconPath>
  <IconPath>/usr/share/icons/gnome/256x256/status</IconPath>
  <IconPath>/usr/share/icons/gnome/32x32/actions</IconPath>
  <IconPath>/usr/share/icons/gnome/32x32/animations</IconPath>
  <IconPath>/usr/share/icons/gnome/32x32/apps</IconPath>
  <IconPath>/usr/share/icons/gnome/32x32/categories</IconPath>
  <IconPath>/usr/share/icons/gnome/32x32/devices</IconPath>
  <IconPath>/usr/share/icons/gnome/32x32/emblems</IconPath>
  <IconPath>/usr/share/icons/gnome/32x32/mimetypes</IconPath>
  <IconPath>/usr/share/icons/gnome/32x32/places</IconPath>
  <IconPath>/usr/share/icons/gnome/32x32/status</IconPath>
  <IconPath>/usr/share/icons/gnome/scalable/actions</IconPath>
  <IconPath>/usr/share/icons/gnome/scalable/apps</IconPath>
  <IconPath>/usr/share/icons/gnome/scalable/categories</IconPath>
  <IconPath>/usr/share/icons/gnome/scalable/devices</IconPath>
  <IconPath>/usr/share/icons/gnome/scalable/emblems</IconPath>
  <IconPath>/usr/share/icons/gnome/scalable/mimetypes</IconPath>
  <IconPath>/usr/share/icons/gnome/scalable/places</IconPath>
  <IconPath>/usr/share/icons/gnome/scalable/status</IconPath>"
[[ -d "/usr/share/icons/hicolor/" ]] && ICONS_LIST="$ICONS_LIST
  <IconPath>/usr/share/icons/hicolor/256x256/apps</IconPath>
  <IconPath>/usr/share/icons/hicolor/256x256/mimetypes</IconPath>
  <IconPath>/usr/share/icons/hicolor/32x32/actions</IconPath>
  <IconPath>/usr/share/icons/hicolor/32x32/apps</IconPath>
  <IconPath>/usr/share/icons/hicolor/32x32/categories</IconPath>
  <IconPath>/usr/share/icons/hicolor/32x32/devices</IconPath>
  <IconPath>/usr/share/icons/hicolor/32x32/emblems</IconPath>
  <IconPath>/usr/share/icons/hicolor/32x32/mimetypes</IconPath>
  <IconPath>/usr/share/icons/hicolor/32x32/places</IconPath>
  <IconPath>/usr/share/icons/hicolor/32x32/status</IconPath>
  <IconPath>/usr/share/icons/hicolor/512x512/apps</IconPath>
  <IconPath>/usr/share/icons/hicolor/512x512/mimetypes</IconPath>
  <IconPath>/usr/share/icons/hicolor/scalable/actions</IconPath>
  <IconPath>/usr/share/icons/hicolor/scalable/apps</IconPath>
  <IconPath>/usr/share/icons/hicolor/scalable/categories</IconPath>
  <IconPath>/usr/share/icons/hicolor/scalable/devices</IconPath>
  <IconPath>/usr/share/icons/hicolor/scalable/emblems</IconPath>
  <IconPath>/usr/share/icons/hicolor/scalable/mimetypes</IconPath>
  <IconPath>/usr/share/icons/hicolor/scalable/places</IconPath>
  <IconPath>/usr/share/icons/hicolor/scalable/status</IconPath>"
[[ -d "/usr/share/icons/Numix/" ]] && ICONS_LIST="  <IconPath>/usr/share/icons/Numix/128@2x/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/128@2x/places</IconPath>
  <IconPath>/usr/share/icons/Numix/128/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/128/places</IconPath>
  <IconPath>/usr/share/icons/Numix/16@2x/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/16@2x/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/16@2x/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/16@2x/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/16@2x/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/16@2x/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/16@2x/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/16@2x/panel</IconPath>
  <IconPath>/usr/share/icons/Numix/16@2x/places</IconPath>
  <IconPath>/usr/share/icons/Numix/16@2x/status</IconPath>
  <IconPath>/usr/share/icons/Numix/16/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/16/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/16/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/16/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/16/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/16/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/16/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/16/panel</IconPath>
  <IconPath>/usr/share/icons/Numix/16/places</IconPath>
  <IconPath>/usr/share/icons/Numix/16/status</IconPath>
  <IconPath>/usr/share/icons/Numix/22@2x/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/22@2x/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/22@2x/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/22@2x/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/22@2x/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/22@2x/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/22@2x/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/22@2x/panel</IconPath>
  <IconPath>/usr/share/icons/Numix/22@2x/places</IconPath>
  <IconPath>/usr/share/icons/Numix/22@2x/status</IconPath>
  <IconPath>/usr/share/icons/Numix/22/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/22/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/22/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/22/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/22/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/22/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/22/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/22/panel</IconPath>
  <IconPath>/usr/share/icons/Numix/22/places</IconPath>
  <IconPath>/usr/share/icons/Numix/22/status</IconPath>
  <IconPath>/usr/share/icons/Numix/24@2x/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/24@2x/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/24@2x/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/24@2x/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/24@2x/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/24@2x/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/24@2x/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/24@2x/panel</IconPath>
  <IconPath>/usr/share/icons/Numix/24@2x/places</IconPath>
  <IconPath>/usr/share/icons/Numix/24@2x/status</IconPath>
  <IconPath>/usr/share/icons/Numix/24/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/24/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/24/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/24/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/24/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/24/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/24/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/24/panel</IconPath>
  <IconPath>/usr/share/icons/Numix/24/places</IconPath>
  <IconPath>/usr/share/icons/Numix/24/status</IconPath>
  <IconPath>/usr/share/icons/Numix/256@2x/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/256@2x/places</IconPath>
  <IconPath>/usr/share/icons/Numix/256/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/256/places</IconPath>
  <IconPath>/usr/share/icons/Numix/32@2x/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/32@2x/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/32@2x/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/32@2x/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/32@2x/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/32@2x/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/32@2x/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/32@2x/places</IconPath>
  <IconPath>/usr/share/icons/Numix/32@2x/status</IconPath>
  <IconPath>/usr/share/icons/Numix/32/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/32/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/32/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/32/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/32/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/32/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/32/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/32/places</IconPath>
  <IconPath>/usr/share/icons/Numix/32/status</IconPath>
  <IconPath>/usr/share/icons/Numix/48@2x/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/48@2x/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/48@2x/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/48@2x/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/48@2x/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/48@2x/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/48@2x/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/48@2x/notifications</IconPath>
  <IconPath>/usr/share/icons/Numix/48@2x/places</IconPath>
  <IconPath>/usr/share/icons/Numix/48@2x/status</IconPath>
  <IconPath>/usr/share/icons/Numix/48/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/48/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/48/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/48/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/48/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/48/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/48/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/48/notifications</IconPath>
  <IconPath>/usr/share/icons/Numix/48/places</IconPath>
  <IconPath>/usr/share/icons/Numix/48/status</IconPath>
  <IconPath>/usr/share/icons/Numix/64@2x/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/64@2x/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/64@2x/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/64@2x/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/64@2x/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/64@2x/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/64@2x/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/64@2x/places</IconPath>
  <IconPath>/usr/share/icons/Numix/64@2x/status</IconPath>
  <IconPath>/usr/share/icons/Numix/64/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/64/animations</IconPath>
  <IconPath>/usr/share/icons/Numix/64/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/64/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/64/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/64/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/64/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/64/places</IconPath>
  <IconPath>/usr/share/icons/Numix/64/status</IconPath>
  <IconPath>/usr/share/icons/Numix/96@2x/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/96@2x/places</IconPath>
  <IconPath>/usr/share/icons/Numix/96/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/96/places</IconPath>
  <IconPath>/usr/share/icons/Numix/scalable/actions</IconPath>
  <IconPath>/usr/share/icons/Numix/scalable/apps</IconPath>
  <IconPath>/usr/share/icons/Numix/scalable/categories</IconPath>
  <IconPath>/usr/share/icons/Numix/scalable/devices</IconPath>
  <IconPath>/usr/share/icons/Numix/scalable/emblems</IconPath>
  <IconPath>/usr/share/icons/Numix/scalable/mimetypes</IconPath>
  <IconPath>/usr/share/icons/Numix/scalable/places</IconPath>
  <IconPath>/usr/share/icons/Numix/scalable/status</IconPath>
$ICONS_LIST"
  myICONS=("/usr/share/pixmaps" "/usr/share/icons" "/usr/share/app-install/icons")
  for i in "${myICONS[@]}"
  do  
     ICONS_LIST="$ICONS_LIST
   <IconPath>$i</IconPath>"
  done
fi
## list up top
for i in "${iconDIRS[@]}"
do
   [[ -d "$i" ]] && ICONS_LIST="$ICONS_LIST
   <IconPath>$i</IconPath>"
   [[ "${i/\$HOME}" != "${i}" ]] && ICONS_LIST="$ICONS_LIST
   <IconPath>$i</IconPath>"
done

MOUSE="<DoubleClickSpeed>400</DoubleClickSpeed>
    <DoubleClickDelta>2</DoubleClickDelta>"
AERGROUP="<Group>
        <Option>aerosnap</Option>
    </Group>"

WINDOW_GROUPS="<Group>
        <Option>noshade</Option>
    </Group>
    <Group>
        <Class>Pidgin</Class>
        <Option>sticky</Option>
    </Group>
    <Group>
        <Name>gkrellm</Name>
        <Option>nolist</Option>
        <Option>sticky</Option>
    </Group>
    <Group>
        <Name>conky</Name>
        <Option>nolist</Option>
        <Option>sticky</Option>
    </Group>"
export WINDOW_GROUPS
#####################################################################################
### End Variables
THEMEfiles=("Default" "Ambiance" "DarkGnome2" "LightGnome2" "Bassem" "Numix" )
defaulttheme(){
TRAY="${DEFAULT_TRAY}"
OLD_TRAY="${OLD_DEFAULT_TRAY}"
MENUS_LIST="${REGULAR_MENUS_LIST}"
TASK_ACTIVE_FOREGROUND="#FFFFFF"
TASK_ACTIVE_BACKGROUND="#5A584F"
TASK_BACKGROUND="#383838"
TASK_FOREGROUND="#ffffff"
TRAY_FOREGROUND="#ffffff"
TRAY_BACKGROUND="#383838"
TRAY_OPACITY="0.75"
TRAY_BUTTON_FOREGROUND="#ffffff"
TRAY_BUTTON_BACKGROUND="#383838"
PAGER_OUTLINE="#000000"
PAGER_FOREGROUND="#808080"
PAGER_BACKGROUND="#383838"
PAGER_ACTIVE_FOREGROUND="#ffffff"
PAGER_ACTIVE_BACKGROUND="#940000"
MENU_FOREGROUND="#ffffff"
MENU_BACKGROUND="#383838"
MENU_ACTIVE_FOREGROUND="#ffffff"
MENU_ACTIVE_BACKGROUND="#940000"
MENU_OPACITY="0.85"
WINDOW_ACTIVE_FOREGROUND="#ffffff"
WINDOW_ACTIVE_BACKGROUND="#383838:#232323"
WINDOW_ACTIVE_OUTLINE="#232323"
WINDOW_ACTIVE_OPACITY="1.0"
WINDOW_FOREGROUND="#5A584F"
WINDOW_BACKGROUND="#000000"
WINDOW_OUTLINE="#000000"
WINDOW_OPACITY="0.7"
POPUP_OUTLINE="#000000"
POPUP_FOREGROUND="#ffffff"
POPUP_BACKGROUND="#383838"
BUTTONS="<ButtonClose>$INSTDIR/Buttons/Default/close.png</ButtonClose>
    <ButtonMax>$INSTDIR/Buttons/Default/max.png</ButtonMax>
    <ButtonMaxActive>$INSTDIR/Buttons/Default/max-toggle.png</ButtonMaxActive>
    <ButtonMin>$INSTDIR/Buttons/Default/min.png</ButtonMin>"
}
ambiancetheme(){
TRAY="${DEFAULT_TRAY}"
OLD_TRAY="${OLD_DEFAULT_TRAY}"
MENUS_LIST="${REGULAR_MENUS_LIST}"
BUTTONS="<ButtonClose>$INSTDIR/Buttons/Ambiance/close.png</ButtonClose>
    <ButtonMax>$INSTDIR/Buttons/Ambiance/max.png</ButtonMax>
    <ButtonMaxActive>$INSTDIR/Buttons/Ambiance/max_toggled.png</ButtonMaxActive>
    <ButtonMin>$INSTDIR/Buttons/Ambiance/iconify.png</ButtonMin>"
TASK_ACTIVE_FOREGROUND="#ffffff"
TASK_ACTIVE_BACKGROUND="#484741"
TASK_BACKGROUND="#484741"
TASK_FOREGROUND="#ffffff"
TRAY_FOREGROUND="#ffffff"
TRAY_BACKGROUND="#484741"
TRAY_OPACITY="0.75"
TRAY_BUTTON_FOREGROUND="#ffffff"
TRAY_BUTTON_BACKGROUND="#484741"
PAGER_OUTLINE="#000000"
PAGER_FOREGROUND="#808080"
PAGER_BACKGROUND="#383838"
PAGER_ACTIVE_FOREGROUND="#ffffff"
PAGER_ACTIVE_BACKGROUND="#E45C2D"
MENU_FOREGROUND="#ffffff"
MENU_BACKGROUND="#383838"
MENU_ACTIVE_FOREGROUND="#ffffff"
MENU_ACTIVE_BACKGROUND="#E45C2D"
MENU_OPACITY="0.85"
WINDOW_ACTIVE_FOREGROUND="#ffffff"
WINDOW_ACTIVE_BACKGROUND="#5A584F:#484741"
WINDOW_ACTIVE_OUTLINE="#484741"
WINDOW_ACTIVE_OPACITY="1.0"
WINDOW_FOREGROUND="#ffffff"
WINDOW_BACKGROUND="#5A584F:#484741"
WINDOW_OUTLINE="#000000"
WINDOW_OPACITY="0.7"
POPUP_OUTLINE="#000000"
POPUP_FOREGROUND="#ffffff"
POPUP_BACKGROUND="#484741"
}
darkgnome2theme(){
TRAY="${DEFAULT_TRAY}"
OLD_TRAY="${OLD_DEFAULT_TRAY}"
MENUS_LIST="${REGULAR_MENUS_LIST}"
TASK_ACTIVE_FOREGROUND="#ffffff"
TASK_ACTIVE_BACKGROUND="#A5A5A5"
TASK_BACKGROUND="#595959"
TASK_FOREGROUND="#BFBFBF"
TRAY_FOREGROUND="#ffffff"
TRAY_BACKGROUND="#464646"
TRAY_OPACITY="0.75"
TRAY_BUTTON_FOREGROUND="#ffffff"
TRAY_BUTTON_BACKGROUND="#464646"
PAGER_OUTLINE="#000000"
PAGER_FOREGROUND="#ffffff"
PAGER_BACKGROUND="#58564D"
PAGER_ACTIVE_FOREGROUND="#ffffff"
PAGER_ACTIVE_BACKGROUND="#406477"
MENU_FOREGROUND="#ffffff"
MENU_BACKGROUND="#58564D"
MENU_ACTIVE_FOREGROUND="#ffffff"
MENU_ACTIVE_BACKGROUND="#406477"
MENU_OPACITY="0.85"
WINDOW_ACTIVE_FOREGROUND="#ffffff"
WINDOW_ACTIVE_BACKGROUND="#58564D:#383838"
WINDOW_ACTIVE_OUTLINE="#353535"
WINDOW_ACTIVE_OPACITY="1.0"
WINDOW_FOREGROUND="#A1A1A1"
WINDOW_BACKGROUND="#58564D:#46443F"
WINDOW_OUTLINE="#353535"
WINDOW_OPACITY="0.7"
POPUP_OUTLINE="#000000"
POPUP_FOREGROUND="#ffffff"
POPUP_BACKGROUND="#464646"
BUTTONS="<ButtonClose>$INSTDIR/Buttons/Default/close.png</ButtonClose>
    <ButtonMax>$INSTDIR/Buttons/Default/max.png</ButtonMax>
    <ButtonMaxActive>$INSTDIR/Buttons/Default/max-toggle.png</ButtonMaxActive>
    <ButtonMin>$INSTDIR/Buttons/Default/min.png</ButtonMin>"
}
lightgnome2theme(){
TRAY="${DEFAULT_TRAY}"
OLD_TRAY="${OLD_DEFAULT_TRAY}"
MENUS_LIST="${REGULAR_MENUS_LIST}"
TASK_ACTIVE_FOREGROUND="#000000"
TASK_ACTIVE_BACKGROUND="#C2C2BE"
TASK_BACKGROUND="#E2E2DE"
TASK_FOREGROUND="#BFBFBF"
TRAY_FOREGROUND="#000000"
TRAY_BACKGROUND="#E2E2DE"
TRAY_OPACITY="0.75"
TRAY_BUTTON_FOREGROUND="#000000"
TRAY_BUTTON_BACKGROUND="#E2E2DE"
PAGER_OUTLINE="#000000"
PAGER_FOREGROUND="#ffffff"
PAGER_BACKGROUND="#353535"
PAGER_ACTIVE_FOREGROUND="#ffffff"
PAGER_ACTIVE_BACKGROUND="#406477"
MENU_FOREGROUND="#000000"
MENU_BACKGROUND="#E2E2DE"
MENU_ACTIVE_FOREGROUND="#000000"
MENU_ACTIVE_BACKGROUND="#406477"
MENU_OPACITY="0.85"
WINDOW_ACTIVE_FOREGROUND="#000000"
WINDOW_ACTIVE_BACKGROUND="#E2E2DE:#CCCCCC"
WINDOW_ACTIVE_OUTLINE="#989898"
WINDOW_ACTIVE_OPACITY="1.0"
WINDOW_FOREGROUND="#2E2E2E"
WINDOW_BACKGROUND="#E2E2DE:#979797"
WINDOW_OUTLINE="#353535"
WINDOW_OPACITY="0.7"
POPUP_OUTLINE="#000000"
POPUP_FOREGROUND="#000000"
POPUP_BACKGROUND="#353535"
BUTTONS="<ButtonClose>$INSTDIR/Buttons/Default/close.png</ButtonClose>
    <ButtonMax>$INSTDIR/Buttons/Default/max.png</ButtonMax>
    <ButtonMaxActive>$INSTDIR/Buttons/Default/max-toggle.png</ButtonMaxActive>
    <ButtonMin>$INSTDIR/Buttons/Default/min.png</ButtonMin>"
}
baseemtheme(){

TRAY="<Tray x=\"0\" y=\"-1\" height=\"34\" valign=\"top\" width=\"0\" halign=\"fixed\" layout=\"horizontal\">
		<TrayButton icon=\"${MENU_ICON}\" border=\"false\">${TORI_ROOT}</TrayButton>
        <Spacer/>
        ${CLOCK_TAG}
        <Spacer/>
        <TrayButton label=\"${SHUTDOWN_NAME}\" icon=\"${SHUTDOWN_ICON}\" border=\"false\">${SHUTDOWN_ROOT}</TrayButton>
    </Tray>
    <Tray x=\"0\" y=\"-1\" height=\"34\" valign=\"bottom\" width=\"0\" halign=\"fixed\" layout=\"horizontal\">
        <Pager labeled=\"true\"/>
        <TaskList maxwidth=\"256\"/>"
[[ -n "$(which xload)" ]] && TRAY="$TRAY
        <Swallow name=\"xload\" width=\"64\">xload -nolabel -bg DimGrey -fg Grey -hl DarkGrey</Swallow>"

TRAY="$TRAY
		<TrayButton label=\"${PLACES_NAME}\" icon=\"${PLACES_ICON}\" border=\"false\">${PLACES_ROOT}</TrayButton>
        <Dock/>
    </Tray>"
OLD_TRAY="<Tray x=\"0\" y=\"-1\" height=\"34\" valign=\"top\" width=\"0\" halign=\"fixed\" layout=\"horizontal\">
<TrayButton icon=\"${MENU_ICON}\" border=\"false\">${TORI_ROOT}</TrayButton>
        <Spacer/>
        ${OLD_CLOCK_TAG}
        <Spacer/>
        <TrayButton label=\"${SHUTDOWN_NAME}\" icon=\"${SHUTDOWN_ICON}\" border=\"false\">${SHUTDOWN_ROOT}</TrayButton>
    </Tray>
    <Tray x=\"0\" y=\"-1\" height=\"34\" valign=\"bottom\" width=\"0\" halign=\"fixed\" layout=\"horizontal\">
        <Pager labeled=\"true\"/>
        <TaskList maxwidth=\"256\"/>"
[[ -n "$(which xload)" ]] && OLD_TRAY="$OLD_TRAY
        <Swallow name=\"xload\" width=\"64\">xload -nolabel -bg DimGrey -fg Grey -hl DarkGrey</Swallow>"
OLD_TRAY="$OLD_TRAY
		<TrayButton label=\"${PLACES_NAME}\" icon=\"${PLACES_ICON}\" border=\"false\">${PLACES_ROOT}</TrayButton>
        <Dock/>
    </Tray>"
MENUS_LIST="${REGULAR_MENUS_LIST}"
TASK_ACTIVE_FOREGROUND="#ffffff"
TASK_ACTIVE_BACKGROUND="#4A24AB"
TASK_BACKGROUND="#353535"
TASK_FOREGROUND="#BFBFBF"
TRAY_FOREGROUND="#ffffff"
TRAY_BACKGROUND="#353535"
TRAY_OPACITY="0.75"
TRAY_BUTTON_FOREGROUND="#ffffff"
TRAY_BUTTON_BACKGROUND="#353535"
PAGER_OUTLINE="#000000"
PAGER_FOREGROUND="#ffffff"
PAGER_BACKGROUND="#353535"
PAGER_ACTIVE_FOREGROUND="#ffffff"
PAGER_ACTIVE_BACKGROUND="#4A24AB"
MENU_FOREGROUND="#ffffff"
MENU_BACKGROUND="#353535"
MENU_ACTIVE_FOREGROUND="#ffffff"
MENU_ACTIVE_BACKGROUND="#4A24AB"
MENU_OPACITY="0.85"
WINDOW_ACTIVE_FOREGROUND="#eaeaea"
WINDOW_ACTIVE_BACKGROUND="#737373:#353535"
WINDOW_ACTIVE_OUTLINE="#353535"
WINDOW_ACTIVE_OPACITY="1.0"
WINDOW_FOREGROUND="#6E35FF"
WINDOW_BACKGROUND="#737373:#353535"
WINDOW_OUTLINE="#353535"
WINDOW_OPACITY="0.7"
POPUP_OUTLINE="#000000"
POPUP_FOREGROUND="#ffffff"
POPUP_BACKGROUND="#353535"
BUTTONS="<ButtonClose>$INSTDIR/Buttons/Default/close.png</ButtonClose>
    <ButtonMax>$INSTDIR/Buttons/Default/max.png</ButtonMax>
    <ButtonMaxActive>$INSTDIR/Buttons/Default/max-toggle.png</ButtonMaxActive>
    <ButtonMin>$INSTDIR/Buttons/Default/min.png</ButtonMin>"
}
numixtheme(){
TRAY="${DEFAULT_TRAY}"
OLD_TRAY="${OLD_DEFAULT_TRAY}"
MENUS_LIST="${REGULAR_MENUS_LIST}"
CORNER="0"
BUTTONS="<ButtonClose>$RELINSTDIR/Numix/unity/close_focused_prelight.png</ButtonClose>
    <ButtonMax>$RELINSTDIR/Numix/unity/maximize_focused_normal.png</ButtonMax>
    <ButtonMaxActive>$RELINSTDIR/Numix/unity/unmaximize.png</ButtonMaxActive>
    <ButtonMin>$RELINSTDIR/Numix/unity/minimize.png</ButtonMin>"
TASK_ACTIVE_FOREGROUND="#f9f9f9"
TASK_ACTIVE_BACKGROUND="#d64937"
TASK_BACKGROUND="#2d2d2d"
TASK_FOREGROUND="#dcdcdc"
TRAY_FOREGROUND="#dcdcdc"
TRAY_BACKGROUND="#2d2d2d"
TRAY_OPACITY="1.0"
TRAY_BUTTON_FOREGROUND="#dcdcdc"
TRAY_BUTTON_BACKGROUND="#2d2d2d"
PAGER_OUTLINE="#000000"
PAGER_FOREGROUND="#2d2d2d"
PAGER_BACKGROUND="#888888"
PAGER_ACTIVE_FOREGROUND="#f9f9f9"
PAGER_ACTIVE_BACKGROUND="#d64937"
MENU_FOREGROUND="#dcdcdc"
MENU_BACKGROUND="#2d2d2d"
MENU_ACTIVE_FOREGROUND="#f9f9f9"
MENU_ACTIVE_BACKGROUND="#d64937"
MENU_OPACITY="1.0"
W_HEIGHT="30"
WINDOW_ACTIVE_FOREGROUND="#dcdcdc"
WINDOW_ACTIVE_BACKGROUND="#2d2d2d"
WINDOW_ACTIVE_OUTLINE="#484848"
WINDOW_ACTIVE_OPACITY="1.0"
WINDOW_FOREGROUND="#888888"
WINDOW_BACKGROUND="#2d2d2d"
WINDOW_OUTLINE="#393939"
WINDOW_OPACITY="1.0"
POPUP_OUTLINE="#484848"
POPUP_FOREGROUND="#2d2d2d"
POPUP_BACKGROUND="#2d2d2d"
}
oldthemes(){
  export JWMRC_TEXT="<?xml version=\"1.0\"?>
<JWM>
<!-- MENUS -->
    <!-- Main Menu -->
    $MENUS_LIST
    <RootMenu onroot=\"1\"/>
    <!-- Mouse Menu-->
    $MOUSE_MENU
    <!--Shudown Menu-->
    <RootMenu height=\"0\" onroot=\"9\">
        $SHUTERDOWN
    </RootMenu>
<!-- END MENUS -->
<!-- GROUP -->
    $WINDOW_GROUPS
<!-- PANEL -->
    $OLD_TRAY
<!-- Panel Style -->
    <TaskListStyle>
        <ActiveForeground>$TASK_ACTIVE_FOREGROUND</ActiveForeground>
        <ActiveBackground>$TASK_ACTIVE_BACKGROUND</ActiveBackground>
        <Background>$TASK_BACKGROUND</Background>
        <Foreground>$TASK_FOREGROUND</Foreground>
        <Font>$FONT</Font>
    </TaskListStyle>
    <TrayStyle>
        <Font>$FONT</Font>
        <Foreground>$TRAY_FOREGROUND</Foreground>
        <Background>$TRAY_BACKGROUND</Background>
        <Opacity>$TRAY_OPACITY</Opacity>
    </TrayStyle>
    <TrayButtonStyle>
	<Font>$FONT</Font>
        <Foreground>$TRAY_BUTTON_FOREGROUND</Foreground>
        <Background>$TRAY_BUTTON_BACKGROUND</Background>
    </TrayButtonStyle>
    <PagerStyle>
        <Outline>$PAGER_OUTLINE</Outline>
        <Foreground>$PAGER_FOREGROUND</Foreground>
        <Background>$PAGER_BACKGROUND</Background>
        <Text>$PAGER_ACTIVE_FOREGROUND</Text>
        <ActiveForeground>$PAGER_ACTIVE_FOREGROUND</ActiveForeground>
        <ActiveBackground>$PAGER_ACTIVE_BACKGROUND</ActiveBackground>
    </PagerStyle>
    <MenuStyle>
        <Font>$FONT</Font>
        <Foreground>$MENU_FOREGROUND</Foreground>
        <Background>$MENU_BACKGROUND</Background>
        <ActiveBackground>$MENU_ACTIVE_BACKGROUND</ActiveBackground>
        <Opacity>$MENU_OPACITY</Opacity>
    </MenuStyle>
<!-- WINDOW -->
    <WindowStyle>
        <Font>$FONT</Font>
        <Width>4</Width>
        <Height>$W_HEIGHT</Height>
        <Active>
            <Text>$WINDOW_ACTIVE_FOREGROUND</Text>
            <Title>$WINDOW_ACTIVE_BACKGROUND</Title>
            <Outline>$WINDOW_ACTIVE_OUTLINE</Outline>
            <Opacity>$WINDOW_ACTIVE_OPACITY</Opacity>
        </Active>
		<Text>$WINDOW_FOREGROUND</Text>
		<Title>$WINDOW_BACKGROUND</Title>
		<Outline>$WINDOW_OUTLINE</Outline>
		<Opacity>$WINDOW_OPACITY</Opacity>
    </WindowStyle>
    <FocusModel>click</FocusModel>
    <SnapMode distance=\"10\">border</SnapMode>
    <MoveMode>opaque</MoveMode>
    <ResizeMode>opaque</ResizeMode>
<!-- KEYSHORTCUTS -->
    $KEYSHORTCUTS
<!-- MOUSE -->
    $MOUSE
<!-- ICONS -->
    $ICONS_LIST
<!-- DESKTOP -->
    <Desktops width=\"2\" height=\"1\">
        <Background type=\"image\">$BG</Background>
    </Desktops>
<!-- AUTOSTART -->
   $STARTUP
<!--POP UP -->
    <PopupStyle>
        <Font>$FONT</Font>
        <Outline>$POPUP_OUTLINE</Outline>
        <Foreground>$POPUP_FOREGROUND</Foreground>
        <Background>$POPUP_BACKGROUND</Background>
    </PopupStyle>
</JWM>"
}
newthemes(){
  export JWMRC_TEXT="<?xml version=\"1.0\"?>
<JWM>
<!-- MENUS -->
    <!-- Main Menu -->
    $MENUS_LIST
    <RootMenu height=\"0\" onroot=\"z\">
        <Exit label=\"Logout\" confirm=\"false\" icon=\"$LOGOUT_ICON$\"/>
    </RootMenu>
    <RootMenu onroot=\"1\"/>
    <!--Traybutton Edit Menu-->
$EDIT_PANEL
$EDIT_MENU
    <!-- Mouse Menu-->
    $MOUSE_MENU
    <!--Shudown Menu-->
    <RootMenu height=\"0\" onroot=\"9\">
        $SHUTERDOWN
    </RootMenu>
$CLOCK_MENU
<!-- END MENUS -->
<!-- GROUP -->
    $WINDOW_GROUPS
<!-- PANEL -->
	$TRAY
<!-- Panel Style -->
    <TaskListStyle>
        <Font>$FONT</Font>
        <Active>
		<Foreground>$TASK_ACTIVE_FOREGROUND</Foreground>
		<Background>$TASK_ACTIVE_BACKGROUND</Background>
        </Active>
        <Foreground>$TASK_FOREGROUND</Foreground>
        <Background>$TASK_BACKGROUND</Background>
    </TaskListStyle>
    <TrayStyle>
        <Font>$FONT</Font>
        <Foreground>$TRAY_FOREGROUND</Foreground>
        <Background>$TRAY_BACKGROUND</Background>
        <Opacity>$TRAY_OPACITY</Opacity>
    </TrayStyle>
    <TrayButtonStyle>
	<Font>$FONT</Font>
        <Foreground>$TRAY_BUTTON_FOREGROUND</Foreground>
        <Background>$TRAY_BUTTON_BACKGROUND</Background>
    </TrayButtonStyle>
    <PagerStyle>
        <Active>
		<Foreground>$PAGER_ACTIVE_FOREGROUND</Foreground>
		<Background>$PAGER_ACTIVE_BACKGROUND</Background>
        </Active>
        <Text>$PAGER_ACTIVE_FOREGROUND</Text>
        <Outline>$PAGER_OUTLINE</Outline>
        <Foreground>$PAGER_FOREGROUND</Foreground>
        <Background>$PAGER_BACKGROUND</Background>
    </PagerStyle>
    <MenuStyle>
        <Font>$FONT</Font>
        <Active>
	        <Foreground>$MENU_ACTIVE_FOREGROUND</Foreground>
		<Background>$MENU_ACTIVE_BACKGROUND</Background>
        </Active>
        <Foreground>$MENU_FOREGROUND</Foreground>
        <Background>$MENU_BACKGROUND</Background>
        <Opacity>$MENU_OPACITY</Opacity>
    </MenuStyle>
<!-- WINDOW -->
    <WindowStyle>
        <Corner>$CORNER</Corner>
        <Font>$FONT</Font>
        <Width>4</Width>
        <Height>$W_HEIGHT</Height>
        <Active>
            <Foreground>$WINDOW_ACTIVE_FOREGROUND</Foreground>
            <Background>$WINDOW_ACTIVE_BACKGROUND</Background>
            <Outline>$WINDOW_ACTIVE_OUTLINE</Outline>
            <Opacity>$WINDOW_ACTIVE_OPACITY</Opacity>
        </Active>
		<Foreground>$WINDOW_FOREGROUND</Foreground>
		<Background>$WINDOW_BACKGROUND</Background>
		<Outline>$WINDOW_OUTLINE</Outline>
		<Opacity>$WINDOW_OPACITY</Opacity>
    </WindowStyle>
    $BUTTONS
    <FocusModel>click</FocusModel>
    <SnapMode distance=\"10\">border</SnapMode>
    <MoveMode>opaque</MoveMode>
    <ResizeMode>opaque</ResizeMode>
<!-- KEYSHORTCUTS -->
    $NEW_KEYSHORTCUTS
<!-- MOUSE -->
    $MOUSE
<!-- ICONS -->
    $ICONS_LIST
<!-- DESKTOP -->
    <Desktops width=\"2\" height=\"1\">
        <Background type=\"image\">$BG</Background>
    </Desktops>
<!-- AUTOSTART -->
   $STARTUP
<!--POP UP -->
    <PopupStyle>
        <Font>$FONT</Font>
        <Outline>$POPUP_OUTLINE</Outline>
        <Foreground>$POPUP_FOREGROUND</Foreground>
        <Background>$POPUP_BACKGROUND</Background>
    </PopupStyle>
</JWM>"
}
newestthemes(){
  export JWMRC_TEXT="<?xml version=\"1.0\"?>
<JWM>
<!-- MENUS -->
    <!-- Main Menu -->
    $MENUS_LIST_NEW
    <RootMenu height=\"0\" onroot=\"z\">
        <Exit label=\"Logout\" confirm=\"false\" icon=\"$LOGOUT_ICON$\"/>
    </RootMenu>
    <RootMenu onroot=\"1\"/>
    <!--Traybutton Edit Menu-->
$EDIT_PANEL
$EDIT_MENU
    <!-- Mouse Menu-->
    $MOUSE_MENU
    <!--Shudown Menu-->
    <RootMenu height=\"0\" onroot=\"9\">
        $SHUTERDOWN
    </RootMenu>
$CLOCK_MENU
<!-- END MENUS -->
<!-- GROUP -->
    $WINDOW_GROUPS
    $AERGROUP
<!-- PANEL -->
    $TRAY
<!-- Panel Style -->
    <TrayStyle group=\"true\">
        <Font>$FONT</Font>
        <Foreground>$TRAY_FOREGROUND</Foreground>
        <Background>$TRAY_BACKGROUND</Background>
        <Opacity>$TRAY_OPACITY</Opacity>
    </TrayStyle>
    <PagerStyle>
        <Active>
		<Foreground>$PAGER_ACTIVE_FOREGROUND</Foreground>
		<Background>$PAGER_ACTIVE_BACKGROUND</Background>
        </Active>
        <Text>$PAGER_ACTIVE_FOREGROUND</Text>
        <Outline>$PAGER_OUTLINE</Outline>
        <Foreground>$PAGER_FOREGROUND</Foreground>
        <Background>$PAGER_BACKGROUND</Background>
    </PagerStyle>
    <MenuStyle>
        <Font>$FONT</Font>
        <Active>
	        <Foreground>$MENU_ACTIVE_FOREGROUND</Foreground>
		<Background>$MENU_ACTIVE_BACKGROUND</Background>
        </Active>
        <Foreground>$MENU_FOREGROUND</Foreground>
        <Background>$MENU_BACKGROUND</Background>
        <Opacity>$MENU_OPACITY</Opacity>
    </MenuStyle>
<!-- WINDOW -->
    <WindowStyle>
        <Corner>$CORNER</Corner>
        <Font>$FONT</Font>
        <Width>4</Width>
        <Height>$W_HEIGHT</Height>
        <Active>
            <Foreground>$WINDOW_ACTIVE_FOREGROUND</Foreground>
            <Background>$WINDOW_ACTIVE_BACKGROUND</Background>
            <Outline>$WINDOW_ACTIVE_OUTLINE</Outline>
            <Opacity>$WINDOW_ACTIVE_OPACITY</Opacity>
        </Active>
		<Foreground>$WINDOW_FOREGROUND</Foreground>
		<Background>$WINDOW_BACKGROUND</Background>
		<Outline>$WINDOW_OUTLINE</Outline>
		<Opacity>$WINDOW_OPACITY</Opacity>
    </WindowStyle>
    $BUTTONS
    <FocusModel>click</FocusModel>
    <SnapMode distance=\"10\">border</SnapMode>
    <MoveMode>opaque</MoveMode>
    <ResizeMode>opaque</ResizeMode>
<!-- KEYSHORTCUTS -->
    $NEW_KEYSHORTCUTS
<!-- MOUSE -->
    $MOUSE
<!-- ICONS -->
    $ICONS_LIST
<!-- DESKTOP -->
    <Desktops width=\"2\" height=\"1\">
        <Background type=\"image\">$BG</Background>
    </Desktops>
<!-- AUTOSTART -->
   $STARTUP
<!--POP UP -->
    <PopupStyle>
        <Font>$FONT</Font>
        <Outline>$POPUP_OUTLINE</Outline>
        <Foreground>$POPUP_FOREGROUND</Foreground>
        <Background>$POPUP_BACKGROUND</Background>
    </PopupStyle>
</JWM>"
}
maketheme(){
  OUTFILE="$1"
  DIR="$2"
  FILE="$DIR/2.3.0/$OUTFILE/$OUTFILE"
  [[ -d "$DIR/2.3.0/$OUTFILE" ]] || mkdir -p "$DIR/2.3.0/$OUTFILE"
  newestthemes && [[ -n "$JWMRC_TEXT" ]] && echo "$JWMRC_TEXT" | sudo tee "$FILE" > /dev/null
  FILE="$DIR/$OUTFILE/$OUTFILE"
  [[ -d "$DIR/$OUTFILE" ]] || mkdir -p "$DIR/$OUTFILE"
  newthemes && [[ -n "$JWMRC_TEXT" ]] && echo "$JWMRC_TEXT" | sudo tee "$FILE" > /dev/null
  [[ -d "$DIR/old/$OUTFILE" ]] || mkdir -p "$DIR/old/$OUTFILE"
  FILE="$DIR/old/$OUTFILE/$OUTFILE"
  oldthemes && [[ -n "$JWMRC_TEXT" ]] && echo "$JWMRC_TEXT" | sudo tee "$FILE" > /dev/null
}
skelfile(){
	FILE="/etc/skel/.jwmrc"
	defaulttheme
	case $JWMver in
		"new")newestthemes&& [[ -n "$JWMRC_TEXT" ]] && echo "$JWMRC_TEXT" | sudo tee "$FILE" > /dev/null
			;;
		"mid")newthemes&& [[ -n "$JWMRC_TEXT" ]] && echo "$JWMRC_TEXT" | sudo tee "$FILE" > /dev/null
			;;
		"old")oldthemes&& [[ -n "$JWMRC_TEXT" ]] && echo "$JWMRC_TEXT" | sudo tee "$FILE" > /dev/null
			;;
	esac
    LOG "Modify $FILE for the $JWMver version of JWM"
}
configure_file(){
  OUTFILE="$1"
  DIR="$2"

  themesAVIL=("Default" "Ambiance" "DarkGnome2" "LightGnome2" "Bassem" "Numix" )
for thisTHEME in "${themesAVIL[@]}"
do
  LOG "Generating $thisTHEME in $DIR"
  case $thisTHEME in
   "Ambiance")
      ambiancetheme
      maketheme "$thisTHEME" "$DIR"
      ;;
   "DarkGnome2")
      darkgnome2theme
      maketheme "$thisTHEME" "$DIR"
      ;;
   "LightGnome2")
      lightgnome2theme
      maketheme "$thisTHEME" "$DIR"
      ;;
   "Bassem")
      baseemtheme
      maketheme "$thisTHEME" "$DIR"
      ;;
   "Numix")
      numixtheme
      maketheme "$thisTHEME" "$DIR"
      ;;
   *)
      defaulttheme
      maketheme "$thisTHEME" "$DIR"
      ;;
  esac
done
}
for i in "${THEMEfiles[@]}"
do
  echo "Configuring $i"
  configure_file "$i" "$INSTDIR/themes/"
done
exit 0
